/**
 * Nhóm D · Quản trị (spec v3) — D-00 đăng nhập · D-01 tổng quan · D-02 thành viên · D-03 đơn & đối soát ·
 * D-04 sản phẩm & bảng hoa hồng · D-05 kho mã & thiết bị · D-06 hạng & quy tắc · D-07 rút tiền & sổ hoa hồng ·
 * D-08 ngoại lệ (ẩn) · D-09 duyệt đăng ký · D-10 tài khoản admin (Head)
 */
const Admin = {
  st: { period: 'month', users: { q: '', type: '', rank: '', status: '', page: 1 }, orders: { tab: 'all', q: '', status: '', page: 1 }, codes: { q: '', status: '', page: 1 }, d07: { tab: 'withdraw', wdStatus: '', wdPage: 1, cmQ: '', cmPage: 1 }, regs: { status: '', q: '', page: 1 } },
  me: function() { return Store.currentAdmin(); },
  isHead: function() { return Store.isHead(); },
  periodDays: function() { return { week: 7, month: 30, quarter: 90 }[this.st.period] || 30; },
  periodSeg: function() { return `<div class="seg" role="group" aria-label="Kỳ">${CONFIG.periods.filter(p => p.id !== 'custom').map(p => `<button class="${this.st.period === p.id ? 'is-active' : ''}" onclick="Admin.st.period='${p.id}'; App.reload()">${p.label}</button>`).join('')}</div>`; },
  approvalCell: function(e) {
    const ap = (e.approvals || []).filter(a => a.action === 'APPROVE'); const rej = (e.approvals || []).find(a => a.action === 'REJECT');
    return `${UI.badge(e.status.startsWith('PENDING') || e.status === 'APPROVED' || e.status === 'REJECTED' ? (e.amount !== undefined ? 'withdrawal' : 'approval') : 'approval', e.status)}${ap.map(a => `<span class="cell-sub">${UI.icon('check', 12)} ${UI.esc(a.by)} · ${UI.esc(LABELS.role[a.role] ? LABELS.role[a.role].text : a.role)} · ${UI.dt(a.at)}</span>`).join('')}${rej ? `<span class="cell-sub text-error">${UI.esc(rej.by)}: ${UI.esc(rej.reason || '')}</span>` : ''}`;
  },
  canApproveBtn: function(e) { const me = this.me(); if (!e.status.startsWith('PENDING')) return { ok: false }; if ((e.approvals || []).some(a => a.by === me.username && a.action === 'APPROVE')) return { ok: false, why: 'Bạn đã xác nhận' }; if (e.createdBy === me.username) return { ok: false, why: 'Người tạo hộ không tự duyệt' }; return { ok: true }; },
  timeline: function(e, extra) { const rows = [{ at: e.createdAt, text: 'Tạo' + (e.createdBy && e.createdBy !== 'agent' ? ' (tạo hộ bởi ' + e.createdBy + ')' : ' bởi thành viên') }].concat((e.approvals || []).map((a, i) => ({ at: a.at, text: (a.action === 'APPROVE' ? 'Xác nhận' : 'Từ chối') + ' — ' + a.by + ' (' + (LABELS.role[a.role] ? LABELS.role[a.role].text : a.role) + ')' + (a.reason ? ': ' + a.reason : '') }))).concat(extra || []); return `<ul class="timeline">${rows.map(r => `<li><span class="timeline-time">${UI.dt(r.at)}</span><span class="timeline-text">${UI.esc(r.text)}</span></li>`).join('')}</ul>`; },
  auditList: function(entity, id) { const list = Store.auditOf(entity, id); return list.length ? `<ul class="timeline">${list.map(a => `<li><span class="timeline-time">${UI.dt(a.at)}</span><span class="timeline-text"><strong>${UI.esc(a.actor)}</strong> ${a.from || a.to ? `<span class="mono">${UI.esc(a.from || '—')} → ${UI.esc(a.to || '—')}</span> ` : ''}${UI.esc(a.note || '')}</span></li>`).join('')}</ul>` : '<p class="text-muted">Chưa có</p>'; },

  // =====================================================================
  // D-00 · Đăng nhập quản trị
  // =====================================================================
  D00: function(q) {
    if (Store.currentAdmin()) { App.navigate(q.get('next') ? decodeURIComponent(q.get('next')) : 'D-01', { replace: true }); return ''; }
    this._next = q.get('next') ? decodeURIComponent(q.get('next')) : 'D-01';
    return `<div class="admin-login"><div class="admin-login-side"><div>${UI.logo({ size: 40, invert: true })}</div><div><h2>Khu vực quản trị HOMI365</h2><p>Duyệt đăng ký thành viên, đối soát đơn hàng, quản lý kho mã & thiết bị, bảng hoa hồng theo hạng, duyệt rút tiền 2 lớp.</p></div><p class="text-sm" style="color:var(--sky-200)">${UI.esc(CONFIG.brand.company)}</p></div>
      <div class="admin-login-form"><div class="card"><div class="card-body"><h1>Đăng nhập quản trị</h1><p class="text-muted mt-1 mb-4">Tài khoản do Head Admin cấp. Thành viên vui lòng đăng nhập tại <a href="#A-05">cổng thành viên</a>.</p>
        <form novalidate onsubmit="Admin.login(event)">${UI.field({ id: 'ad-user', label: 'Tên đăng nhập', required: true, attrs: 'autocomplete="username"' })}
          <div class="field mt-4" id="ad-pass-field"><label class="field-label" for="ad-pass">Mật khẩu<span class="req">*</span></label><div class="input-affix"><input class="input" type="password" id="ad-pass" autocomplete="current-password" required><button type="button" class="btn btn-ghost affix-btn" aria-label="Hiện mật khẩu" onclick="UI.togglePassword('ad-pass', this)">${UI.icon('eye', 20)}</button></div><div class="field-error" id="ad-pass-err"></div></div>
          <div id="ad-alert" class="mt-4" hidden></div><div class="actions"><button class="btn btn-primary btn-lg btn-block" id="ad-submit">${UI.icon('lock', 18)} Đăng nhập</button></div></form>
        <div class="demo-hint">Demo: <strong>head</strong> (Head Admin) · <strong>admin</strong> · <strong>admin2</strong> (Specialist) / mật khẩu <strong>${CONFIG.admin.accounts[0].password}</strong></div></div></div></div></div>`;
  },
  login: function(e) { e.preventDefault(); const user = UI.val('ad-user'), pass = UI.val('ad-pass'); const box = document.getElementById('ad-alert'); UI.setError('ad-user', ''); UI.setError('ad-pass', ''); box.hidden = true; let ok = true; if (!user) { UI.setError('ad-user', 'Nhập tên đăng nhập.'); ok = false; } if (!pass) { UI.setError('ad-pass', 'Nhập mật khẩu.'); ok = false; } if (!ok) { UI.focusFirstError(); return; } const btn = document.getElementById('ad-submit'); UI.setLoading(btn, true); setTimeout(() => { UI.setLoading(btn, false); const r = Store.adminLogin(user, pass); if (r.ok) { App.navigate(this._next || 'D-01'); return; } box.hidden = false; box.innerHTML = r.locked ? `<div class="alert alert-error" role="alert">${UI.icon('lock', 20)}<div><span class="alert-title">Tài khoản tạm khoá</span>Nhập sai quá ${CONFIG.admin.maxLoginFail} lần. Thử lại sau ${r.minutes} phút.</div></div>` : `<div class="alert alert-error" role="alert">${UI.icon('x-circle', 20)}<div>Tên đăng nhập hoặc mật khẩu không đúng (hoặc tài khoản bị vô hiệu). Còn ${r.remaining} lần thử.</div></div>`; }, 400); },

  // =====================================================================
  // D-01 · Tổng quan
  // =====================================================================
  D01: function() {
    const days = this.periodDays(); const s = Store.adminStats(days); const series = Store.adminSeries(days).map(x => ({ label: UI.dayLabel(x.date), bar: x.revenue / 1000000 }));
    const todo = [[s.regPending, 'Hồ sơ đăng ký thành viên chờ duyệt', 'Duyệt 2 lớp: Specialist ×2 hoặc Head Admin', 'D-09'], [s.withdrawPending, 'Yêu cầu rút tiền chờ duyệt', 'Đối chiếu số dư rồi xác nhận / từ chối', 'D-07?tab=withdraw'], [s.withdrawApproved, 'Rút tiền đã duyệt, chờ chi trả', 'Xuất file ngân hàng, đánh dấu đã chi trả', 'D-07?tab=withdraw'], [s.awaiting, 'Đơn chuyển khoản chờ đối soát', 'Xác nhận để cấp mã và ghi hoa hồng', 'D-03?tab=awaiting'], [s.lateCallbacks, 'Callback cổng đến sau khi đơn hết hạn', 'Cần kiểm tra thủ công', 'D-03?tab=late'], [s.licensePending, 'Đơn đã thanh toán chưa có mã', 'Kho hết — bổ sung mã', 'D-05'], [s.stock <= CONFIG.stock.lowThreshold ? 1 : 0, 'Kho mã sắp cạn', `Còn ${s.stock} mã, ngưỡng ${CONFIG.stock.lowThreshold}`, 'D-05']].filter(t => t[0] > 0);
    const html = `<div class="stack-lg"><div class="row-between"><p class="text-muted">Số liệu ${days} ngày gần nhất</p>${this.periodSeg()}</div>
      <div class="stat-grid stat-grid-6">
        <div class="stat stat-navy"><div class="stat-label">${UI.icon('bars', 16)} Doanh thu</div><div class="stat-value">${UI.money(s.revenue)}</div><div class="stat-sub">${s.paid} đơn thanh toán · về công ty ${UI.money(s.companyCommission)}</div></div>
        <div class="stat"><div class="stat-label">${UI.icon('inbox', 16)} Số đơn</div><div class="stat-value">${UI.num(s.orders)}</div></div>
        <div class="stat"><div class="stat-label">${UI.icon('users', 16)} Thành viên mới</div><div class="stat-value">${UI.num(s.newAgents)}</div><div class="stat-sub">${Store.agents().length} thành viên tổng</div></div>
        <div class="stat stat-clickable ${s.regPending ? 'stat-accent' : ''}" onclick="App.navigate('D-09')"><div class="stat-label">${UI.icon('user', 16)} Đăng ký chờ duyệt</div><div class="stat-value ${s.regPending ? 'text-warning' : ''}">${UI.num(s.regPending)}</div></div>
        <div class="stat stat-clickable" onclick="App.navigate('D-07?tab=withdraw')"><div class="stat-label">${UI.icon('cash', 16)} Rút tiền chờ duyệt</div><div class="stat-value ${s.withdrawPending ? 'text-warning' : ''}">${UI.num(s.withdrawPending)}</div><div class="stat-sub">${s.withdrawApproved} chờ chi trả</div></div>
        <div class="stat stat-clickable" onclick="App.navigate('D-05')"><div class="stat-label">${UI.icon('key', 16)} Mã còn trong kho</div><div class="stat-value ${s.stock <= CONFIG.stock.lowThreshold ? 'text-warning' : ''}">${UI.num(s.stock)}</div></div>
      </div>
      <div class="split-2"><div class="stack">
        <div class="card"><div class="card-head"><h2>Doanh thu theo ngày (triệu đồng)</h2></div><div class="card-body">${UI.chart.combo(series, { height: 240, barName: 'triệu đ', yFormat: (v) => Math.round(v), accent: true, aria: 'Doanh thu theo ngày' })}</div></div>
        <div class="card"><div class="card-head"><h2>Job xét hạng cuối tháng</h2><span class="text-sm text-muted">${UI.esc(Store.rules().rankRules.jobTime || CONFIG.rankRules.jobTime)} · tự động</span></div><div class="card-body">
          <p><strong>${s.noSaleAgents}</strong> thành viên chưa bán đủ ${Store.rules().rankRules.minSalesPerMonth} gói trong tháng này (sẽ giáng 1 bậc nếu không phát sinh đơn). Thành viên đủ luỹ kế sẽ được thăng thẳng lên hạng tương ứng.</p>
          ${this.isHead() ? `<div class="actions actions-row"><button class="btn btn-primary" onclick="Admin.runJob()">${UI.icon('zap', 18)} Chạy xét hạng ngay (mô phỏng)</button></div>` : '<p class="text-caption mt-2">Chỉ Head Admin mới chạy thủ công.</p>'}</div></div>
      </div>
      <div class="card"><div class="card-head"><h2>Việc cần làm</h2><span class="badge badge-warning">${todo.length}</span></div><div class="card-body">${todo.length ? `<ul class="todo-list">${todo.map(t => `<li><span class="todo-count">${t[0]}</span><div class="todo-text">${t[1]}<small>${t[2]}</small></div><a class="btn btn-secondary btn-sm" href="#${t[3]}">Xử lý ${UI.icon('arrow-right', 14)}</a></li>`).join('')}</ul>` : UI.empty('check-circle', 'Không có việc tồn đọng')}</div></div></div></div>`;
    return App.adminShell('D-01', 'Tổng quan', html);
  },
  runJob: function() { UI.confirm({ title: 'Chạy job xét hạng cuối tháng?', body: 'Mô phỏng job chạy 0h ngày cuối tháng: thành viên bán < 1 gói bị giáng 1 bậc, thành viên đủ luỹ kế được thăng hạng. Kết quả ghi vào lịch sử hạng.', confirmText: 'Chạy ngay', onConfirm: () => { const r = Store.runMonthEndJob(this.me()); UI.modal({ title: 'Kết quả xét hạng', body: `<div class="stack"><div class="alert alert-success">${UI.icon('check-circle', 18)}<div><strong>${r.promoted.length}</strong> thăng hạng · <strong>${r.demoted.length}</strong> giáng hạng</div></div>${r.promoted.length ? `<h3>Thăng hạng</h3><ul class="stack-sm" style="padding-left:18px">${r.promoted.map(p => `<li>${UI.esc(p.user.fullName)}: ${RULES.rank(p.from).label} → <strong>${RULES.rank(p.to).label}</strong> (luỹ kế ${p.user.cumulativeSales})</li>`).join('')}</ul>` : ''}${r.demoted.length ? `<h3>Giáng hạng</h3><ul class="stack-sm" style="padding-left:18px">${r.demoted.map(p => `<li>${UI.esc(p.user.fullName)}: ${RULES.rank(p.from).label} → <strong>${RULES.rank(p.to).label}</strong></li>`).join('')}</ul>` : ''}</div>`, foot: `<button class="btn btn-primary" onclick="UI.closeModal(); App.reload()">Đóng</button>` }); } }); },

  // =====================================================================
  // D-02 · Thành viên
  // =====================================================================
  D02: function() {
    const f = this.st.users;
    const html = `<div class="card"><div class="card-body"><div class="table-toolbar">
        <div class="field field-search"><label class="field-label" for="u-q">Tìm kiếm</label><input class="input" id="u-q" placeholder="Tên, SĐT, ref_code, alias" value="${UI.esc(f.q)}" oninput="Admin.st.users.q=this.value; Admin.st.users.page=1; Admin.renderUsers()"></div>
        <div class="field"><label class="field-label" for="u-type">Loại</label><select class="select" id="u-type" onchange="Admin.st.users.type=this.value; Admin.st.users.page=1; Admin.renderUsers()"><option value="">Tất cả</option><option value="agent" ${f.type === 'agent' ? 'selected' : ''}>Thành viên</option><option value="buyer" ${f.type === 'buyer' ? 'selected' : ''}>Người mua chưa đăng ký</option></select></div>
        <div class="field"><label class="field-label" for="u-rank">Hạng</label><select class="select" id="u-rank" onchange="Admin.st.users.rank=this.value; Admin.st.users.page=1; Admin.renderUsers()"><option value="">Tất cả</option>${CONFIG.ranks.map(r => `<option value="${r.id}" ${f.rank === r.id ? 'selected' : ''}>${r.label}</option>`).join('')}</select></div>
        <div class="field"><label class="field-label" for="u-status">Trạng thái</label><select class="select" id="u-status" onchange="Admin.st.users.status=this.value; Admin.st.users.page=1; Admin.renderUsers()"><option value="">Tất cả</option><option value="active" ${f.status === 'active' ? 'selected' : ''}>Đang hoạt động</option><option value="locked" ${f.status === 'locked' ? 'selected' : ''}>Đã khoá</option></select></div>
        <div class="toolbar-actions"><button class="btn btn-secondary" onclick="Admin.exportUsers()">${UI.icon('download', 16)} Xuất Excel</button></div></div>
      <div id="u-table">${UI.skeletonTable(9, 6)}</div></div></div>`;
    App.after(() => UI.withLoading('u-table', UI.skeletonTable(9, 6), () => this.renderUsers()));
    return App.adminShell('D-02', 'Thành viên', html, { actions: this.isHead() ? `<button class="btn btn-primary" onclick="Admin.rootAgentModal()">${UI.icon('plus', 16)} Tạo thành viên gốc</button>` : '' });
  },
  filteredUsers: function() { const f = this.st.users; const q = f.q.toLowerCase(); return Store.users().filter(u => (!f.type || u.type === f.type) && (!f.rank || u.rank === f.rank) && (!f.status || u.status === f.status) && (!q || u.fullName.toLowerCase().includes(q) || u.phone.includes(q) || (u.refCode || '').toLowerCase().includes(q) || (u.purchaseAlias || '').toLowerCase().includes(q))).sort((a, b) => a.createdAt < b.createdAt ? 1 : -1); },
  renderUsers: function() {
    const el = document.getElementById('u-table'); if (!el) return; const list = this.filteredUsers(); const pg = UI.paginate(list, this.st.users.page);
    if (!list.length) { el.innerHTML = UI.empty('users', 'Không có người dùng phù hợp', 'Thử bỏ bớt bộ lọc.', `<button class="btn btn-secondary" onclick="Admin.st.users={q:'',type:'',rank:'',status:'',page:1}; App.reload()">Xoá bộ lọc</button>`); return; }
    el.innerHTML = `<div class="table-wrap"><table class="table"><thead><tr><th>Thành viên</th><th>Loại</th><th>ref_code</th><th>Link cá nhân</th><th>Tuyến trên</th><th>Hạng</th><th class="num">Đơn đã bán</th><th class="num">Tuyến dưới</th><th>Tham gia</th><th>Trạng thái</th><th></th></tr></thead>
      <tbody>${pg.rows.map(u => { const ref = u.referrerId ? Store.user(u.referrerId) : null; return `<tr><td><span class="cell-main">${UI.esc(u.fullName)}</span><span class="cell-sub mono">${UI.esc(u.phone)}</span></td><td>${UI.badge('userType', u.type)}</td><td class="mono">${UI.esc(u.refCode || '—')}</td><td class="mono">${UI.esc(u.purchaseAlias || '—')}</td><td>${ref ? UI.esc(ref.fullName) + '<span class="cell-sub mono">' + UI.esc(ref.refCode) + '</span>' : '—'}</td><td>${u.rank ? UI.badge('rank', u.rank) : '—'}</td><td class="num">${Store.ordersBySeller(u.id).filter(o => o.status === 'PAID').length}${u.type === 'agent' ? `<span class="cell-sub">luỹ kế ${u.cumulativeSales}</span>` : ''}</td><td class="num">${Store.downline(u.id).filter(x => x.type === 'agent').length}</td><td>${UI.date(u.activatedAt || u.createdAt)}</td><td>${UI.badge('user', u.status)}</td><td><div class="row-actions"><button class="btn btn-secondary btn-sm" onclick="Admin.userDrawer('${u.id}')">Chi tiết</button></div></td></tr>`; }).join('')}</tbody></table></div>${UI.pagination(pg, 'Admin.gotoUsers')}`;
  },
  gotoUsers: function(p) { this.st.users.page = p; this.renderUsers(); },
  exportUsers: function() { UI.exportCsv('thanh-vien.csv', ['Họ tên', 'SĐT', 'Email', 'Loại', 'ref_code', 'Link cá nhân', 'Tuyến trên', 'Hạng', 'Luỹ kế', 'Đơn đã bán', 'Tuyến dưới', 'Trạng thái', 'Tham gia'], this.filteredUsers().map(u => [u.fullName, u.phone, u.email || '', LABELS.userType[u.type].text, u.refCode || '', u.purchaseAlias || '', u.referrerId ? Store.user(u.referrerId).refCode : '', u.rank ? RULES.rank(u.rank).label : '', u.cumulativeSales || 0, Store.ordersBySeller(u.id).filter(o => o.status === 'PAID').length, Store.downline(u.id).length, LABELS.user[u.status].text, UI.date(u.createdAt)])); },
  treeHtml: function(nodes) { if (!nodes.length) return ''; return `<ul class="tree">${nodes.map(n => `<li><span class="tree-node"><strong>${UI.esc(n.user.fullName)}</strong> ${n.user.rank ? UI.badge('rank', n.user.rank) : UI.badge('userType', 'buyer')} <span class="text-sm text-muted">· ${Store.ordersBySeller(n.user.id).filter(o => o.status === 'PAID').length} đơn · <span class="mono">${UI.esc(n.user.refCode || n.user.phone)}</span></span> <button class="btn-link" onclick="Admin.userDrawer('${n.user.id}')">Xem</button></span>${this.treeHtml(n.children)}</li>`).join('')}</ul>`; },
  userDrawer: function(id) {
    const u = Store.user(id); const chain = u.referrerId ? Store.uplineChain(u.referrerId, 99) : []; const tree = Store.downlineTree(id, 3); const bought = Store.ordersByPhone(u.phone); const sold = Store.ordersBySeller(id); const w = Store.wallet(id); const cms = Store.commissionsOf(id).sort((a, b) => a.createdAt < b.createdAt ? 1 : -1); const head = this.isHead();
    UI.drawer({ title: `<h2>${UI.esc(u.fullName)}</h2><div class="row-wrap mt-1">${UI.badge('userType', u.type)}${u.rank ? UI.badge('rank', u.rank) : ''}${UI.badge('user', u.status)}<span class="text-sm text-muted mono">${UI.esc(u.id)}</span></div>`,
      body: `<div class="section"><div class="section-title">Hồ sơ</div><dl class="dl"><dt>SĐT</dt><dd class="mono">${UI.esc(u.phone)}</dd><dt>Email</dt><dd>${UI.esc(u.email || '—')}</dd><dt>Địa chỉ</dt><dd>${UI.esc(u.address || '—')}</dd><dt>ref_code</dt><dd class="mono">${UI.esc(u.refCode || '—')}</dd><dt>Link cá nhân</dt><dd class="mono">${u.purchaseAlias ? UI.esc(RULES.publicPurchaseUrl(u.purchaseAlias)) : '—'}</dd><dt>TK nhận hoa hồng</dt><dd>${u.bank ? UI.esc(u.bank.bankName) + ' · <span class="mono">' + UI.esc(u.bank.accountNo) + '</span> · ' + UI.esc(u.bank.owner) : '—'}</dd><dt>T&C</dt><dd>${u.tcConsent ? 'v' + UI.esc(u.tcConsent.version) + ' · ' + UI.dt(u.tcConsent.at) : '—'}</dd><dt>Tham gia</dt><dd>${UI.dt(u.activatedAt || u.createdAt)}</dd>${u.status === 'locked' ? `<dt>Lý do khoá</dt><dd class="text-error">${UI.esc(u.lockedReason)} (${UI.dt(u.lockedAt)})</dd>` : ''}</dl></div>
        ${u.type === 'agent' ? `<div class="section"><div class="row-between"><div class="section-title">Hạng & điểm</div>${head ? `<button class="btn btn-secondary btn-sm" onclick="Admin.assignRankModal('${u.id}')">${UI.icon('edit', 14)} Chỉ định hạng</button>` : ''}</div><dl class="dl"><dt>Hạng</dt><dd>${UI.badge('rank', u.rank)} từ ${UI.date(u.rankSince)}</dd><dt>Luỹ kế / tháng này</dt><dd>${u.cumulativeSales} gói · ${Store.salesThisMonth(u.id)} gói tháng này</dd><dt>Hoa hồng ghi nhận</dt><dd>${UI.money(w.recorded)} (${UI.num(w.points)} điểm)</dd><dt>Khả dụng / đang giữ / đã rút</dt><dd>${UI.money(w.available)} · ${UI.money(w.held)} · ${UI.money(w.withdrawn)}</dd></dl>
          <div class="section-title mt-3">Lịch sử thăng/giáng hạng</div><ul class="timeline">${(u.rankHistory || []).slice().reverse().map(h => `<li><span class="timeline-time">${UI.dt(h.at)}</span><span class="timeline-text">${UI.badge('rankEvent', h.event)} ${h.from ? RULES.rank(h.from).label + ' → ' : ''}${RULES.rank(h.to).label} · ${UI.esc(h.reason || '')} · ${UI.esc(h.by || '')}</span></li>`).join('')}</ul></div>` : ''}
        <div class="section"><div class="section-title">Tuyến trên (đến gốc)</div>${chain.length ? `<ol class="stack-sm" style="padding-left:20px">${chain.map((c, i) => `<li>F${i + 1}: <strong>${UI.esc(c.fullName)}</strong> ${UI.badge('rank', c.rank)} <span class="mono text-muted">${UI.esc(c.refCode)}</span></li>`).join('')}</ol>` : '<p class="text-muted">Không có (thành viên gốc)</p>'}</div>
        <div class="section"><div class="section-title">Cây tuyến dưới (3 cấp)</div>${tree.length ? this.treeHtml(tree) : '<p class="text-muted">Chưa có</p>'}</div>
        <div class="section"><div class="section-title">Lịch sử đơn</div><dl class="dl"><dt>Đã mua</dt><dd>${bought.length} đơn (${bought.filter(o => o.status === 'PAID').length} thanh toán)</dd><dt>Đã bán (qua link)</dt><dd>${sold.filter(o => o.status === 'PAID').length} / ${sold.length}</dd></dl>${sold.slice(0, 6).map(o => `<div class="row-between text-sm mt-2"><span class="mono">${UI.esc(o.id)}</span><span>${UI.esc(o.fullName)}</span>${UI.badge('orderStatus', o.status)}<button class="btn-link" onclick="Admin.orderDrawer('${o.id}')">Xem</button></div>`).join('')}</div>
        ${u.type === 'agent' ? `<div class="section"><div class="section-title">Lịch sử hoa hồng (${cms.length})</div>${cms.length ? `<div class="table-wrap"><table class="table" style="min-width:0"><thead><tr><th>Ngày</th><th>Đơn</th><th>Nguồn</th><th class="num">Số tiền</th></tr></thead><tbody>${cms.slice(0, 8).map(c => `<tr><td>${UI.date(c.createdAt)}</td><td class="mono">${UI.esc(c.orderId)}</td><td>${Seller.sourceLabel(c)} · ${RULES.rank(c.rankAtCalc).label}</td><td class="num mono">${UI.money(c.amount)}</td></tr>`).join('')}</tbody></table></div>` : '<p class="text-muted">Chưa có</p>'}</div>` : ''}
        <div class="section"><div class="section-title">Nhật ký & audit</div>${this.auditList('user', id)}<ul class="timeline mt-2">${Store.logOf(id).slice(0, 8).map(l => `<li><span class="timeline-time">${UI.dt(l.at)}</span><span class="timeline-text">${UI.esc(l.text)}</span></li>`).join('')}</ul></div>`,
      foot: `${head && u.type === 'agent' ? `<button class="btn btn-secondary" onclick="Admin.changeReferrerModal('${u.id}')">${UI.icon('users', 16)} Đổi người giới thiệu</button>` : ''}${u.status === 'active' ? `<button class="btn btn-danger-outline" onclick="Admin.lockUser('${u.id}')">${UI.icon('lock', 16)} Khoá</button>` : `<button class="btn btn-success" onclick="Admin.unlockUser('${u.id}')">${UI.icon('unlock', 16)} Mở khoá</button>`}` });
  },
  lockUser: function(id) { const u = Store.user(id); UI.confirm({ title: 'Khoá tài khoản?', body: `<strong>${UI.esc(u.fullName)}</strong> sẽ không đăng nhập được; link giới thiệu và link cá nhân ngừng nhận đơn. Hoa hồng đã ghi nhận không bị ảnh hưởng.`, reason: 'Lý do khoá', confirmText: 'Khoá', tone: 'danger', onConfirm: (reason) => { Store.setUserStatus(id, 'locked', reason, this.me()); UI.toast('Đã khoá.'); this.renderUsers(); this.userDrawer(id); } }); },
  unlockUser: function(id) { const u = Store.user(id); UI.confirm({ title: 'Mở khoá?', body: `<strong>${UI.esc(u.fullName)}</strong> đăng nhập và nhận đơn trở lại.`, confirmText: 'Mở khoá', onConfirm: () => { Store.setUserStatus(id, 'active', '', this.me()); UI.toast('Đã mở khoá.'); this.renderUsers(); this.userDrawer(id); } }); },
  changeReferrerModal: function(id) { const u = Store.user(id); const cur = u.referrerId ? Store.user(u.referrerId) : null; UI.modal({ title: 'Đổi người giới thiệu (Head Admin)', sticky: true, body: `<p class="text-muted">${UI.esc(u.fullName)} · hiện tại: ${cur ? UI.esc(cur.fullName) + ' (<span class="mono">' + UI.esc(cur.refCode) + '</span>)' : 'không có'}</p><div class="alert alert-warning mt-3">${UI.icon('warning', 18)}<div class="text-sm">Nguyên tắc chương trình: tuyến được gán 100% chính xác và khoá tại thời điểm mua. Thao tác này là ngoại lệ, chỉ ảnh hưởng đơn phát sinh sau thời điểm đổi, bắt buộc lý do và được ghi audit.</div></div><div class="mt-4">${UI.field({ id: 'cr-code', label: 'ref_code người giới thiệu mới', required: true, mono: true, placeholder: 'VD: BINH88' })}</div><div class="mt-4">${UI.field({ id: 'cr-reason', label: 'Lý do', required: true, type: 'textarea', rows: 2 })}</div>`, foot: `<button class="btn btn-secondary" onclick="UI.closeModal()">Huỷ</button><button class="btn btn-primary" onclick="Admin.changeReferrer('${id}')">Xác nhận đổi</button>` }); },
  changeReferrer: function(id) { const code = UI.val('cr-code').toUpperCase(), reason = UI.val('cr-reason'); const ref = Store.sellerByRef(code); UI.setError('cr-code', ''); UI.setError('cr-reason', ''); if (!ref) { UI.setError('cr-code', 'Không tìm thấy thành viên với mã này.'); return; } if (ref.id === id) { UI.setError('cr-code', 'Không thể tự giới thiệu chính mình.'); return; } if (!reason) { UI.setError('cr-reason', 'Nhập lý do.'); return; } const r = Store.changeReferrer(id, code, reason, this.me()); if (!r.ok) { UI.setError('cr-code', r.message || 'Không hợp lệ.'); return; } UI.closeModal(); UI.toast('Đã đổi người giới thiệu.'); this.renderUsers(); this.userDrawer(id); },
  assignRankModal: function(id) { const u = Store.user(id); UI.modal({ title: 'Chỉ định hạng (Head Admin)', sticky: true, body: `<p class="text-muted">${UI.esc(u.fullName)} · hiện tại ${RULES.rank(u.rank).label} · luỹ kế ${u.cumulativeSales} gói</p><div class="mt-4">${UI.field({ id: 'ar-rank', label: 'Hạng mới', type: 'select', value: u.rank, options: CONFIG.ranks.map(r => ({ value: r.id, label: r.label + ' (ngưỡng ' + r.threshold + ')' })) })}</div><div class="mt-4">${UI.field({ id: 'ar-reason', label: 'Lý do', required: true, type: 'textarea', rows: 2 })}</div>`, foot: `<button class="btn btn-secondary" onclick="UI.closeModal()">Huỷ</button><button class="btn btn-primary" onclick="Admin.assignRank('${id}')">Chỉ định</button>` }); },
  assignRank: function(id) { const rank = UI.val('ar-rank'), reason = UI.val('ar-reason'); UI.setError('ar-reason', ''); if (!reason) { UI.setError('ar-reason', 'Nhập lý do.'); return; } Store.assignRank(id, rank, this.me(), reason); UI.closeModal(); UI.toast('Đã chỉ định hạng ' + RULES.rank(rank).label + '.'); this.renderUsers(); this.userDrawer(id); },
  rootAgentModal: function() { UI.modal({ title: 'Tạo thành viên gốc (Head Admin)', size: 'lg', sticky: true, body: `<p class="text-sm text-muted">Thành viên gốc được kích hoạt ngay, không qua mua hàng và duyệt hồ sơ. Dùng cho đại lý đầu mối.</p><form class="form-grid form-grid-2 mt-3" novalidate>${UI.field({ id: 'ra-name', label: 'Họ và tên', required: true })}${UI.field({ id: 'ra-phone', label: 'Số điện thoại', required: true, mono: true })}${UI.field({ id: 'ra-email', label: 'Email', required: true, type: 'email' })}${UI.field({ id: 'ra-rank', label: 'Hạng khởi điểm', type: 'select', value: 'COPPER', options: CONFIG.ranks.map(r => ({ value: r.id, label: r.label })) })}${UI.field({ id: 'ra-bank', label: 'Ngân hàng', type: 'select', value: CONFIG.banks[0], options: CONFIG.banks.map(b => ({ value: b, label: b })) })}${UI.field({ id: 'ra-acc', label: 'Số tài khoản', mono: true })}${UI.field({ id: 'ra-owner', label: 'Chủ tài khoản' })}${UI.field({ id: 'ra-ref', label: 'ref_code tuyến trên (nếu có)', mono: true, placeholder: 'để trống = gốc' })}${UI.field({ id: 'ra-pw', label: 'Mật khẩu tạm', required: true, value: CONFIG.demo.agentPassword })}<div style="grid-column:1/-1">${UI.field({ id: 'ra-reason', label: 'Lý do', required: true, type: 'textarea', rows: 2 })}</div></form>`, foot: `<button class="btn btn-secondary" onclick="UI.closeModal()">Huỷ</button><button class="btn btn-primary" onclick="Admin.createRootAgent()">Tạo thành viên</button>` }); },
  createRootAgent: function() {
    const name = UI.val('ra-name'), phone = RULES.normalizePhone(UI.val('ra-phone')), email = UI.val('ra-email'), refCode = UI.val('ra-ref').toUpperCase(), reason = UI.val('ra-reason'), pw = UI.val('ra-pw');
    ['ra-name', 'ra-phone', 'ra-email', 'ra-ref', 'ra-reason', 'ra-pw'].forEach(x => UI.setError(x, '')); let ok = true;
    if (name.length < 2) { UI.setError('ra-name', 'Nhập họ tên.'); ok = false; } if (!phone) { UI.setError('ra-phone', 'SĐT không hợp lệ.'); ok = false; } if (!RULES.isEmail(email)) { UI.setError('ra-email', 'Email không hợp lệ.'); ok = false; } if (refCode && !Store.sellerByRef(refCode)) { UI.setError('ra-ref', 'Không tìm thấy ref_code.'); ok = false; } if (!reason) { UI.setError('ra-reason', 'Nhập lý do.'); ok = false; } const pe = RULES.validatePassword(pw); if (pe) { UI.setError('ra-pw', pe); ok = false; } if (!ok) return;
    const r = Store.createRootAgent({ fullName: name, phone, email, rank: UI.val('ra-rank'), bank: { bankName: UI.val('ra-bank'), accountNo: UI.val('ra-acc'), owner: UI.val('ra-owner').toUpperCase() }, referrerId: refCode ? Store.sellerByRef(refCode).id : null, password: pw, reason }, this.me());
    if (!r.ok) { UI.setError('ra-phone', r.message); return; } UI.closeModal(); UI.toast('Đã tạo thành viên ' + r.user.fullName + ' · ref_code ' + r.user.refCode + ' · alias ' + r.user.purchaseAlias); this.renderUsers(); this.userDrawer(r.user.id);
  },

  // =====================================================================
  // D-03 · Đơn hàng & đối soát
  // =====================================================================
  D03: function(q) {
    if (q.get('tab')) { this.st.orders.tab = q.get('tab'); this.st.orders.page = 1; } const f = this.st.orders; const awaiting = Store.orders().filter(o => o.status === 'AWAITING_RECONCILE').length; const late = Store.orders().filter(o => o.flags && o.flags.lateCallback && !o.flags.lateChecked).length;
    const html = `<div class="card"><div class="tabs" role="tablist" style="padding:0 20px"><button class="tab ${f.tab === 'all' ? 'is-active' : ''}" onclick="Admin.st.orders.tab='all'; Admin.st.orders.page=1; App.reload()">Tất cả đơn</button><button class="tab ${f.tab === 'awaiting' ? 'is-active' : ''}" onclick="Admin.st.orders.tab='awaiting'; Admin.st.orders.page=1; App.reload()">Chờ đối soát <span class="count">${awaiting}</span></button><button class="tab ${f.tab === 'late' ? 'is-active' : ''}" onclick="Admin.st.orders.tab='late'; Admin.st.orders.page=1; App.reload()">Callback sau hết hạn <span class="count">${late}</span></button></div>
      <div class="card-body">${f.tab === 'awaiting' ? `<div class="alert alert-info mb-4">${UI.icon('info', 18)}<div class="text-sm">Đối chiếu sao kê theo <strong>nội dung CK = mã đơn</strong> và số tiền. Xác nhận → cấp mã (Đã gắn đơn hàng) + ghi nhận hoa hồng theo chuỗi tuyến ngay.</div></div>` : ''}
        <div class="table-toolbar"><div class="field field-search"><label class="field-label" for="o-q">Tìm kiếm</label><input class="input" id="o-q" placeholder="Mã đơn, tên, SĐT, ref_code" value="${UI.esc(f.q)}" oninput="Admin.st.orders.q=this.value; Admin.st.orders.page=1; Admin.renderOrders()"></div>${f.tab === 'all' ? `<div class="field"><label class="field-label" for="o-status">Trạng thái</label><select class="select" id="o-status" onchange="Admin.st.orders.status=this.value; Admin.st.orders.page=1; Admin.renderOrders()"><option value="">Tất cả</option>${Object.keys(LABELS.orderStatus).map(k => `<option value="${k}" ${f.status === k ? 'selected' : ''}>${LABELS.orderStatus[k].text}</option>`).join('')}</select></div>` : ''}<div class="toolbar-actions"><button class="btn btn-secondary" onclick="Admin.exportOrders()">${UI.icon('download', 16)} Xuất Excel</button></div></div>
        <div id="o-table">${UI.skeletonTable(8, 6)}</div></div></div>`;
    App.after(() => UI.withLoading('o-table', UI.skeletonTable(8, 6), () => this.renderOrders()));
    return App.adminShell('D-03', 'Đơn hàng & đối soát', html);
  },
  filteredOrders: function() { const f = this.st.orders; const q = f.q.toLowerCase(); return Store.orders().filter(o => { if (f.tab === 'awaiting' && o.status !== 'AWAITING_RECONCILE') return false; if (f.tab === 'late' && !(o.flags && o.flags.lateCallback)) return false; if (f.tab === 'all' && f.status && o.status !== f.status) return false; return !q || o.id.toLowerCase().includes(q) || o.fullName.toLowerCase().includes(q) || o.phone.includes(q) || (o.refCode || '').toLowerCase().includes(q); }); },
  renderOrders: function() {
    const el = document.getElementById('o-table'); if (!el) return; const list = this.filteredOrders(); const pg = UI.paginate(list, this.st.orders.page);
    if (!list.length) { el.innerHTML = UI.empty('inbox', 'Không có đơn phù hợp'); return; }
    el.innerHTML = `<div class="table-wrap"><table class="table"><thead><tr><th>Mã đơn</th><th>Người mua</th><th>Người bán</th><th>Hạng lúc đơn</th><th>Phương thức</th><th class="num">Số tiền</th><th>Thanh toán</th><th>Giao hàng</th><th>Mã KH</th><th></th></tr></thead>
      <tbody>${pg.rows.map(o => { const s = o.sellerId ? Store.user(o.sellerId) : null; const c = o.licenseCode ? Store.codeInfo(o.licenseCode) : null; return `<tr><td><span class="cell-main mono">${UI.esc(o.id)}</span><span class="cell-sub">${UI.dt(o.createdAt)}</span></td><td><span class="cell-main">${UI.esc(o.fullName)}</span><span class="cell-sub mono">${UI.esc(o.phone)}</span></td><td>${s ? UI.esc(s.fullName) + '<span class="cell-sub mono">' + UI.esc(o.refCode) + '</span>' : '—'}</td><td>${o.referrerRankAtOrder ? UI.badge('rank', o.referrerRankAtOrder) : '—'}</td><td>${UI.esc(LABELS.method[o.method] || '—')}</td><td class="num mono">${UI.money(o.price)}</td><td>${UI.badge('orderStatus', o.status)}${o.flags && o.flags.lateCallback && !o.flags.lateChecked ? '<span class="cell-sub text-warning">Callback muộn</span>' : ''}${o.refunded ? '<span class="cell-sub text-error">Đã hoàn tiền</span>' : ''}</td><td>${o.status === 'PAID' ? UI.badge('shipping', o.shipping) : '—'}</td><td>${o.status === 'PAID' ? UI.badge('license', c ? c.status : 'PENDING') : '—'}</td><td><div class="row-actions">${o.status === 'AWAITING_RECONCILE' ? `<button class="btn btn-success btn-sm" onclick="Admin.confirmReconcile('${o.id}')">Xác nhận</button><button class="btn btn-danger-outline btn-sm" onclick="Admin.rejectReconcile('${o.id}')">Từ chối</button>` : ''}<button class="btn btn-secondary btn-sm" onclick="Admin.orderDrawer('${o.id}')">Chi tiết</button></div></td></tr>`; }).join('')}</tbody></table></div>${UI.pagination(pg, 'Admin.gotoOrders')}`;
  },
  gotoOrders: function(p) { this.st.orders.page = p; this.renderOrders(); },
  exportOrders: function() { UI.exportCsv('don-hang.csv', ['Mã đơn', 'Ngày', 'Người mua', 'SĐT', 'Email', 'Người bán', 'Hạng lúc đơn', 'Phương thức', 'Số tiền', 'Thanh toán', 'Giao hàng', 'Mã KH'], this.filteredOrders().map(o => [o.id, UI.dt(o.createdAt), o.fullName, o.phone, o.email || '', o.refCode || '', o.referrerRankAtOrder || '', LABELS.method[o.method] || '', o.price, LABELS.orderStatus[o.status].text, RULES.shippingLabel(o.shipping), o.licenseCode || ''])); },
  confirmReconcile: function(id) { const o = Store.order(id); UI.confirm({ title: 'Xác nhận đã nhận chuyển khoản', body: 'Đơn chuyển sang <strong>Đã thanh toán</strong>; hệ thống gắn mã kích hoạt và ghi nhận hoa hồng theo chuỗi tuyến ngay lập tức.', summary: [['Mã đơn', '<span class="mono">' + UI.esc(o.id) + '</span>'], ['Nội dung CK cần khớp', '<span class="mono">' + UI.esc(o.id) + '</span>'], ['Số tiền', UI.money(o.price)], ['Người mua', UI.esc(o.fullName) + ' · ' + UI.esc(o.phone)], ['Kho mã còn', Store.stockCount() + ' mã']], confirmText: 'Xác nhận đã nhận tiền', onConfirm: () => { const r = Store.confirmReconcile(id, this.me()); UI.toast(r.licenseCode ? 'Đã xác nhận. Mã ' + r.licenseCode + ' đã gắn cho đơn.' : 'Đã xác nhận. Kho hết mã — đơn chờ cấp mã.', r.licenseCode ? 'success' : 'warning'); App.reload(); } }); },
  rejectReconcile: function(id) { const o = Store.order(id); UI.confirm({ title: 'Từ chối đối soát', body: `Đơn <span class="mono">${UI.esc(o.id)}</span> của ${UI.esc(o.fullName)} chuyển sang <strong>Bị từ chối</strong>.`, reason: 'Lý do từ chối', confirmText: 'Từ chối', tone: 'danger', onConfirm: (reason) => { Store.rejectReconcile(id, reason, this.me()); UI.toast('Đã từ chối đơn ' + id + '.', 'warning'); App.reload(); } }); },
  commissionAllocation: function(o) {
    const cms = Store.commissionsOfOrder(o.id); if (!cms.length) return '<p class="text-muted">Chưa có (đơn chưa thanh toán hoặc không có người bán).</p>';
    const total = cms.reduce((s, c) => s + (c.status === 'RECORDED' ? c.amount : 0), 0); const expected = RULES.commissionTotal(Store.commissionByRank(o.packageId, o.paidAt)); const rates = Store.commissionByRank(o.packageId, o.paidAt);
    return `<div class="table-wrap"><table class="table" style="min-width:0"><thead><tr><th>Cấp</th><th>Người thụ hưởng</th><th>Hạng lúc tính</th><th class="num">Mức hạng</th><th class="num">Nhận</th><th>TT</th></tr></thead><tbody>${cms.map(c => `<tr><td>${c.kind === 'SELF' ? 'Người bán' : c.kind === 'COMPANY' ? 'Công ty' : 'F' + c.depth}</td><td>${c.beneficiaryId === 'COMPANY' ? '<strong>HOMI365</strong>' : UI.esc(Store.user(c.beneficiaryId).fullName)}</td><td>${UI.badge('rank', c.rankAtCalc)}</td><td class="num mono">${UI.money(rates[c.rankAtCalc] || 0)}</td><td class="num mono text-strong">${UI.money(c.amount)}</td><td>${UI.badge('commission', c.status)}</td></tr>`).join('')}</tbody><tfoot><tr><th colspan="4">Tổng (kiểm: ${UI.money(expected)})</th><th class="num ${total === expected || o.refunded ? 'text-success' : 'text-error'}">${UI.money(total)}</th><th></th></tr></tfoot></table></div>`;
  },
  orderDrawer: function(id) {
    const o = Store.order(id); const s = o.sellerId ? Store.user(o.sellerId) : null; const code = o.licenseCode ? Store.codeInfo(o.licenseCode) : null; const pkg = Store.pkg(o.packageId);
    const tl = [[o.createdAt, 'Tạo đơn (PENDING_PAYMENT)' + (o.refCode ? ' qua link ' + o.refCode : '')]]; if (o.transferClaimedAt) tl.push([o.transferClaimedAt, 'Người mua bấm "Tôi đã chuyển khoản" → chờ đối soát']); if (o.failedAt) tl.push([o.failedAt, 'Cổng trả FAILED: ' + (o.failReason || '')]); if (o.paidAt) tl.push([o.paidAt, (o.method === 'bank' ? 'Admin xác nhận đối soát → ' : 'Callback cổng → ') + 'PAID' + (o.flags && o.flags.lateCallback ? ' (sau khi đơn hết hạn)' : '')]); if (o.reconciledAt && o.status === 'REJECTED') tl.push([o.reconciledAt, 'Admin từ chối: ' + o.rejectReason]); if (code && code.assignedAt) tl.push([code.assignedAt, 'Gắn mã ' + code.code + ' (' + code.deviceSerial + ')']); if (code && code.activatedAt) tl.push([code.activatedAt, 'Kích hoạt trên ' + (code.device ? code.device.name : 'thiết bị')]); (o.shippingLog || []).forEach(l => tl.push([l.at, 'Giao hàng: ' + RULES.shippingLabel(l.step)])); if (o.refundedAt) tl.push([o.refundedAt, 'Hoàn tiền — huỷ hoa hồng']); tl.sort((a, b) => a[0] < b[0] ? -1 : 1);
    const next = RULES.nextShippingStep(o.shipping);
    UI.drawer({ title: `<h2 class="mono">${UI.esc(o.id)}</h2><div class="row-wrap mt-1">${UI.badge('orderStatus', o.status)}${o.status === 'PAID' ? UI.badge('shipping', o.shipping) : ''}${o.flags && o.flags.lateCallback ? '<span class="badge badge-warning">Callback muộn</span>' : ''}${o.refunded ? '<span class="badge badge-error">Đã hoàn tiền</span>' : ''}</div>`,
      body: `<div class="section"><div class="section-title">Đơn hàng</div><dl class="dl"><dt>Gói</dt><dd>${UI.esc(pkg.fullName)}</dd><dt>Số tiền</dt><dd>${UI.money(o.price)}</dd><dt>Phương thức</dt><dd>${UI.esc(LABELS.method[o.method] || '—')}</dd><dt>Tạo lúc</dt><dd>${UI.dt(o.createdAt)}</dd>${o.paidAt ? `<dt>Thanh toán lúc</dt><dd>${UI.dt(o.paidAt)}</dd>` : ''}</dl></div>
        <div class="section"><div class="section-title">Người mua & giao hàng</div><dl class="dl"><dt>Họ tên</dt><dd>${UI.esc(o.fullName)}</dd><dt>SĐT</dt><dd class="mono">${UI.esc(o.phone)}</dd><dt>Email</dt><dd>${UI.esc(o.email || '—')}</dd><dt>Địa chỉ</dt><dd>${UI.esc(o.address)}</dd><dt>Ghi chú</dt><dd>${UI.esc(o.note || '—')}</dd><dt>Người bán</dt><dd>${s ? UI.esc(s.fullName) + ' · <span class="mono">' + UI.esc(o.refCode) + '</span> · ' + (o.referrerRankAtOrder ? RULES.rank(o.referrerRankAtOrder).label + ' lúc đơn' : '') : '—'}</dd></dl>${o.status === 'PAID' && pkg.hasShipping ? `<div class="row-between mt-3"><span>Giao hàng: ${UI.badge('shipping', o.shipping)}</span>${next ? `<button class="btn btn-primary btn-sm" onclick="Admin.updateShipping('${o.id}', '${next}')">${UI.icon('truck', 16)} Chuyển sang "${RULES.shippingLabel(next)}"</button>` : '<span class="text-sm text-success">Đã giao xong</span>'}</div>` : ''}</div>
        <div class="section"><div class="section-title">Mã kích hoạt & thiết bị</div>${code ? `<div class="code-box"><div class="grow"><span class="code-label">${UI.label('license', code.status)} · ${UI.esc(code.deviceSku)} ${UI.esc(code.deviceSerial || '')}</span><span class="code-value">${UI.esc(code.code)}</span></div><button class="btn btn-secondary btn-icon" aria-label="Sao chép" onclick="UI.copy('${code.code}')">${UI.icon('copy', 18)}</button></div>${code.device ? `<p class="text-sm text-muted mt-2">Thiết bị: ${UI.esc(code.device.name)} · <span class="mono">${UI.esc(code.device.deviceId)}</span> · ${UI.dt(code.activatedAt)}</p>` : ''}` : (o.status === 'PAID' ? `<div class="alert alert-warning">${UI.icon('warning', 18)}<div class="text-sm">Đã thanh toán nhưng chưa có mã (kho hết). <a href="#D-05">Bổ sung kho</a>.</div></div>` : '<p class="text-muted">Chưa gắn (đơn chưa thanh toán).</p>')}</div>
        <div class="section"><div class="section-title">Phân bổ hoa hồng theo chuỗi tuyến</div>${this.commissionAllocation(o)}</div>
        <div class="section"><div class="section-title">Dòng thời gian</div><ul class="timeline">${tl.map(t => `<li><span class="timeline-time">${UI.dt(t[0])}</span><span class="timeline-text">${UI.esc(t[1])}</span></li>`).join('')}</ul></div>`,
      foot: `${o.status === 'AWAITING_RECONCILE' ? `<button class="btn btn-danger-outline" onclick="Admin.rejectReconcile('${o.id}')">Từ chối</button><button class="btn btn-success" onclick="Admin.confirmReconcile('${o.id}')">${UI.icon('check', 16)} Xác nhận đã nhận tiền</button>` : ''}${o.flags && o.flags.lateCallback && !o.flags.lateChecked ? `<button class="btn btn-secondary" onclick="Store.clearLateFlag('${o.id}'); UI.toast('Đã đánh dấu kiểm tra.'); App.reload()">${UI.icon('check', 16)} Đã kiểm tra</button>` : ''}${o.status === 'PAID' && !o.refunded ? `<button class="btn btn-danger-outline" onclick="Admin.refundOrder('${o.id}')">Hoàn tiền & huỷ hoa hồng</button>` : ''}` });
  },
  updateShipping: function(id, step) { Store.updateShipping(id, step); UI.toast('Đã cập nhật giao hàng: ' + RULES.shippingLabel(step)); this.renderOrders(); this.orderDrawer(id); },
  refundOrder: function(id) { const n = Store.commissionsOfOrder(id).filter(c => c.status === 'RECORDED').length; UI.confirm({ title: 'Hoàn tiền đơn hàng?', body: `Đơn <span class="mono">${UI.esc(id)}</span> được đánh dấu hoàn tiền; ${n} khoản hoa hồng đã ghi nhận sẽ bị huỷ và trừ khỏi ví các thành viên liên quan.`, reason: 'Lý do hoàn tiền', confirmText: 'Hoàn tiền', tone: 'danger', onConfirm: (reason) => { Store.refundOrder(id, reason, this.me()); UI.toast('Đã hoàn tiền, huỷ ' + n + ' khoản hoa hồng.', 'warning'); App.reload(); } }); },

  // =====================================================================
  // D-04 · Sản phẩm & bảng hoa hồng 6 hạng
  // =====================================================================
  D04: function() {
    const list = Store.packages(); const top = RULES.topRank();
    const html = `<div class="stack-lg"><div class="alert alert-info">${UI.icon('info', 18)}<div class="text-sm">Mỗi gói có <strong>bảng hoa hồng theo 6 hạng</strong> (VNĐ/gói, tăng đơn điệu). Hoa hồng của một đơn = mức ${top.label}, chia theo chênh lệch hạng trên chuỗi tuyến; phần còn dư về công ty. Mỗi lần sửa lưu thành phiên bản có ngày hiệu lực.</div></div>
      <div class="table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Tên gói</th><th class="num">Giá</th><th>Ảnh</th><th class="num">HH ${top.label}</th><th>Bảng HH</th><th>Cập nhật</th><th>Bán</th><th></th></tr></thead><tbody>${list.map(p => `<tr><td class="mono text-strong">${UI.esc(p.id)}</td><td><span class="cell-main">${UI.esc(p.name)}</span><span class="cell-sub">${UI.esc(p.desc).slice(0, 70)}…</span></td><td class="num mono">${UI.money(p.price)}</td><td>${p.image ? `<img src="${UI.esc(p.image)}" alt="" style="width:56px;height:36px;object-fit:cover;border-radius:4px">` : '—'}</td><td class="num mono">${UI.money(RULES.commissionTotal(p.commissionByRank || {}))}</td><td><span class="text-sm">${(p.commissionVersions || []).length} phiên bản</span></td><td>${UI.date(p.updatedAt)}</td><td>${p.active ? '<span class="badge badge-success">Đang bán</span>' : '<span class="badge badge-neutral">Tắt</span>'}</td><td><div class="row-actions"><button class="btn btn-secondary btn-sm" onclick="Admin.packageForm('${p.id}')">${UI.icon('edit', 14)} Sửa</button><button class="btn btn-secondary btn-sm" onclick="Admin.commissionTableModal('${p.id}')">${UI.icon('layers', 14)} Bảng HH</button>${p.active ? `<button class="btn btn-danger-outline btn-sm" onclick="Admin.togglePackage('${p.id}', false)">Tắt bán</button>` : `<button class="btn btn-success btn-sm" onclick="Admin.togglePackage('${p.id}', true)">Bật bán</button>`}</div></td></tr>`).join('')}</tbody></table></div>
      ${list.map(p => `<div class="card"><div class="card-head"><h2>Bảng hoa hồng · ${UI.esc(p.id)} ${UI.esc(p.name)}</h2><button class="btn btn-primary btn-sm" onclick="Admin.commissionTableModal('${p.id}')">${UI.icon('plus', 14)} Phiên bản mới</button></div><div class="card-body">${this.commissionTableHtml(p)}</div></div>`).join('')}</div>`;
    return App.adminShell('D-04', 'Sản phẩm & hoa hồng', html, { actions: `<button class="btn btn-primary" onclick="Admin.packageForm()">${UI.icon('plus', 16)} Thêm gói</button>` });
  },
  commissionTableHtml: function(p) {
    const vs = (p.commissionVersions || []).slice().sort((a, b) => b.version - a.version); const cur = Store.commissionByRank(p.id);
    return `<div class="table-wrap"><table class="table" style="min-width:0"><thead><tr><th>Hạng</th><th class="num">Mức hoa hồng</th><th class="num">Chênh lệch so với hạng dưới</th></tr></thead><tbody>${CONFIG.ranks.map((r, i) => `<tr><td>${UI.badge('rank', r.id)}</td><td class="num mono text-strong">${UI.money(cur[r.id] || 0)}</td><td class="num mono">${i ? '+' + UI.money((cur[r.id] || 0) - (cur[CONFIG.ranks[i - 1].id] || 0)) : '—'}</td></tr>`).join('')}</tbody></table></div>
      <h3 class="mt-4 mb-2">Lịch sử phiên bản</h3>${vs.length ? vs.map((v, i) => { const prev = vs[i + 1]; return `<div class="policy-version ${v.byRank === cur || (i === 0 && v.effectiveFrom <= Store.nowIso()) ? 'is-current' : ''}"><div class="row-between"><strong>v${v.version}</strong>${v.effectiveFrom > Store.nowIso() ? '<span class="badge badge-info">Sắp hiệu lực</span>' : i === 0 ? '<span class="badge badge-success">Đang áp dụng</span>' : '<span class="badge badge-neutral">Đã thay thế</span>'}</div><div class="text-sm text-muted">Hiệu lực ${UI.date(v.effectiveFrom)} · ${UI.esc(v.by)} · ${UI.dt(v.at)}</div><div class="text-sm mt-1">${CONFIG.ranks.map(r => `<span class="mono">${r.label.slice(0, 2)} ${prev && prev.byRank[r.id] !== v.byRank[r.id] ? `<span class="diff-del">${UI.num(prev.byRank[r.id] / 1000)}k</span> <span class="diff-add">${UI.num(v.byRank[r.id] / 1000)}k</span>` : UI.num(v.byRank[r.id] / 1000) + 'k'}</span>`).join(' · ')}</div>${v.note ? `<div class="text-sm text-muted mt-1">"${UI.esc(v.note)}"</div>` : ''}</div>`; }).join('') : '<p class="text-muted">Chưa có</p>'}`;
  },
  commissionTableModal: function(pid) { const p = Store.pkg(pid); const cur = Store.commissionByRank(pid); UI.modal({ title: 'Bảng hoa hồng mới · ' + p.name, size: 'lg', sticky: true, body: `<div class="table-wrap"><table class="table" style="min-width:0"><thead><tr><th>Hạng</th><th>Mức hoa hồng (đ)</th><th class="num">Chênh lệch</th></tr></thead><tbody>${CONFIG.ranks.map((r, i) => `<tr><td>${UI.badge('rank', r.id)}</td><td><input class="input input-mono" id="ct-${r.id}" value="${cur[r.id] || 0}" inputmode="numeric" oninput="Admin.ctRecalc()" aria-label="Mức ${r.label}"></td><td class="num mono" id="ct-diff-${r.id}">${i ? '+' + UI.money((cur[r.id] || 0) - (cur[CONFIG.ranks[i - 1].id] || 0)) : '—'}</td></tr>`).join('')}</tbody></table></div><div class="field-error mt-2" id="ct-err"></div><div class="form-grid form-grid-2 mt-4">${UI.field({ id: 'ct-eff', label: 'Ngày hiệu lực', required: true, type: 'date', value: new Date().toISOString().slice(0, 10) })}${UI.field({ id: 'ct-note', label: 'Ghi chú phiên bản', placeholder: 'Lý do thay đổi…' })}</div><p class="text-caption mt-2">Đơn thanh toán từ ngày hiệu lực áp dụng bảng mới; hoa hồng đã ghi nhận giữ nguyên.</p>`, foot: `<button class="btn btn-secondary" onclick="UI.closeModal()">Huỷ</button><button class="btn btn-primary" onclick="Admin.saveCommissionTable('${pid}')">Lưu phiên bản</button>` }); },
  ctRecalc: function() { CONFIG.ranks.forEach((r, i) => { if (!i) return; const a = Number(UI.val('ct-' + r.id).replace(/\D/g, '')), b = Number(UI.val('ct-' + CONFIG.ranks[i - 1].id).replace(/\D/g, '')); const el = document.getElementById('ct-diff-' + r.id); if (el) { el.textContent = (a - b >= 0 ? '+' : '') + UI.money(a - b); el.className = 'num mono ' + (a < b ? 'text-error' : ''); } }); },
  saveCommissionTable: function(pid) { const byRank = {}; CONFIG.ranks.forEach(r => { byRank[r.id] = Number(UI.val('ct-' + r.id).replace(/\D/g, '')); }); const err = document.getElementById('ct-err'); err.textContent = ''; const eff = UI.val('ct-eff'); if (!eff) { err.textContent = 'Chọn ngày hiệu lực.'; return; } const r = Store.saveCommissionTable(pid, byRank, new Date(eff + 'T00:00:00').toISOString(), UI.val('ct-note'), this.me()); if (!r.ok) { err.textContent = r.message; return; } UI.closeModal(); UI.toast('Đã lưu bảng hoa hồng v' + r.version + '.'); App.reload(); },
  togglePackage: function(id, active) { const p = Store.pkg(id); UI.confirm({ title: active ? 'Bật bán gói?' : 'Tắt bán gói?', body: active ? `Gói <strong>${UI.esc(p.name)}</strong> hiển thị trên trang mua hàng; gói đang bật khác sẽ tự tắt.` : 'Người mua mở link sẽ thấy "Sản phẩm tạm ngưng bán".', confirmText: active ? 'Bật bán' : 'Tắt bán', tone: active ? '' : 'danger', onConfirm: () => { Store.togglePackage(id, active, this.me()); UI.toast(active ? 'Đã bật bán.' : 'Đã tắt bán.'); App.reload(); } }); },
  packageForm: function(id) { const p = id ? Store.pkg(id) : { id: '', name: '', fullName: '', desc: '', price: 0, image: '', licenseMonths: 12, hasShipping: true, benefits: [] }; UI.modal({ title: id ? 'Sửa gói ' + id : 'Thêm gói sản phẩm', size: 'lg', sticky: true, body: `<form class="form-grid form-grid-2" novalidate>${UI.field({ id: 'pk-id', label: 'Mã gói', required: true, mono: true, value: p.id, attrs: id ? 'readonly' : '' })}${UI.field({ id: 'pk-name', label: 'Tên gói', required: true, value: p.name })}${UI.field({ id: 'pk-price', label: 'Giá (đ)', required: true, mono: true, value: p.price, attrs: 'inputmode="numeric"' })}${UI.field({ id: 'pk-image', label: 'Ảnh (đường dẫn)', value: p.image || '', placeholder: './public/product/og-cover.png' })}<div style="grid-column:1/-1">${UI.field({ id: 'pk-full', label: 'Tên đầy đủ hiển thị', required: true, value: p.fullName })}</div><div style="grid-column:1/-1">${UI.field({ id: 'pk-desc', label: 'Mô tả', type: 'textarea', rows: 2, value: p.desc })}</div><div style="grid-column:1/-1">${UI.field({ id: 'pk-benefits', label: 'Quyền lợi (mỗi dòng một mục)', type: 'textarea', rows: 4, value: (p.benefits || []).join('\n') })}</div>${UI.field({ id: 'pk-months', label: 'Thời hạn license (tháng, tuỳ chọn)', mono: true, value: p.licenseMonths || '' })}<label class="check"><input type="checkbox" id="pk-ship" ${p.hasShipping ? 'checked' : ''}> Có giao hàng vật lý</label></form>${!id ? '<p class="text-caption mt-2">Sau khi tạo, thêm bảng hoa hồng 6 hạng bằng nút "Bảng HH".</p>' : ''}`, foot: `<button class="btn btn-secondary" onclick="UI.closeModal()">Huỷ</button><button class="btn btn-primary" onclick="Admin.savePackage(${id ? 'true' : 'false'})">Lưu</button>` }); },
  savePackage: function(editing) { const id = UI.val('pk-id').toUpperCase(), name = UI.val('pk-name'), price = Number(UI.val('pk-price').replace(/\D/g, '')); ['pk-id', 'pk-name', 'pk-price', 'pk-full'].forEach(x => UI.setError(x, '')); let ok = true; if (!/^[A-Z0-9]{2,10}$/.test(id)) { UI.setError('pk-id', 'Mã gói 2–10 ký tự chữ/số.'); ok = false; } if (!editing && Store.pkg(id)) { UI.setError('pk-id', 'Mã gói đã tồn tại.'); ok = false; } if (!name) { UI.setError('pk-name', 'Nhập tên gói.'); ok = false; } if (!(price > 0)) { UI.setError('pk-price', 'Giá phải > 0.'); ok = false; } if (!UI.val('pk-full')) { UI.setError('pk-full', 'Nhập tên đầy đủ.'); ok = false; } if (!ok) return; const ex = Store.pkg(id) || {}; Store.savePackage({ id, name, fullName: UI.val('pk-full'), desc: UI.val('pk-desc'), price, image: UI.val('pk-image'), licenseMonths: Number(UI.val('pk-months')) || 0, hasShipping: document.getElementById('pk-ship').checked, active: !!ex.active, benefits: UI.val('pk-benefits').split('\n').map(s => s.trim()).filter(Boolean) }, this.me()); UI.closeModal(); UI.toast('Đã lưu gói ' + id + '.'); App.reload(); },

  // =====================================================================
  // D-05 · Kho mã & thiết bị (7.8)
  // =====================================================================
  D05: function() {
    const codes = Store.codes(); const f = this.st.codes; const cnt = { IN_STOCK: 0, ASSIGNED: 0, ACTIVATED: 0 }; codes.forEach(c => { cnt[c.status] = (cnt[c.status] || 0) + 1; }); const low = cnt.IN_STOCK <= CONFIG.stock.lowThreshold; const pendingOrders = Store.orders().filter(o => o.status === 'PAID' && !o.licenseCode).length;
    const html = `<div class="stack-lg">${low ? `<div class="alert alert-warning" role="alert">${UI.icon('warning', 20)}<div><span class="alert-title">Kho sắp cạn</span>Còn ${cnt.IN_STOCK} mã sẵn hàng (ngưỡng ${CONFIG.stock.lowThreshold}).</div></div>` : ''}${pendingOrders ? `<div class="alert alert-error" role="alert">${UI.icon('alert-octagon', 20)}<div class="row-between grow"><span><span class="alert-title">${pendingOrders} đơn đã thanh toán chờ gắn mã</span></span><button class="btn btn-primary btn-sm" ${cnt.IN_STOCK ? '' : 'disabled'} onclick="UI.toast('Đã gắn mã cho ' + Store.fulfilPendingLicenses() + ' đơn.'); App.reload()">Gắn mã cho đơn chờ</button></div></div>` : ''}
      <div class="stat-grid" style="grid-template-columns:repeat(4,1fr)"><div class="stat ${low ? 'stat-accent' : ''}"><div class="stat-label">${UI.icon('key', 16)} Sẵn hàng</div><div class="stat-value ${low ? 'text-warning' : ''}">${UI.num(cnt.IN_STOCK)}</div><div class="progress mt-2 ${low ? 'is-low' : ''}"><span style="width:${Math.round(cnt.IN_STOCK / Math.max(1, codes.length) * 100)}%"></span></div></div><div class="stat"><div class="stat-label">${UI.icon('inbox', 16)} Đã gắn đơn hàng</div><div class="stat-value">${UI.num(cnt.ASSIGNED)}</div></div><div class="stat"><div class="stat-label">${UI.icon('device', 16)} Đã kích hoạt</div><div class="stat-value">${UI.num(cnt.ACTIVATED)}</div></div><div class="stat stat-navy"><div class="stat-label">Σ tổng</div><div class="stat-value">${UI.num(codes.length)}</div><div class="stat-sub">${cnt.IN_STOCK} + ${cnt.ASSIGNED} + ${cnt.ACTIVATED} = ${codes.length} ✓</div></div></div>
      <div class="card"><div class="card-body"><div class="table-toolbar"><div class="field field-search"><label class="field-label" for="k-q">Tìm mã / serial / đơn / lô</label><input class="input input-mono" id="k-q" value="${UI.esc(f.q)}" oninput="Admin.st.codes.q=this.value; Admin.st.codes.page=1; Admin.renderCodes()"></div><div class="field"><label class="field-label" for="k-status">Trạng thái</label><select class="select" id="k-status" onchange="Admin.st.codes.status=this.value; Admin.st.codes.page=1; Admin.renderCodes()"><option value="">Tất cả</option>${['IN_STOCK', 'ASSIGNED', 'ACTIVATED'].map(k => `<option value="${k}" ${f.status === k ? 'selected' : ''}>${LABELS.license[k].text}</option>`).join('')}</select></div><div class="toolbar-actions"><button class="btn btn-secondary" onclick="Admin.exportCodes()">${UI.icon('download', 16)} Xuất Excel</button></div></div><div id="k-table">${UI.skeletonTable(7, 8)}</div></div></div></div>`;
    App.after(() => UI.withLoading('k-table', UI.skeletonTable(7, 8), () => this.renderCodes()));
    return App.adminShell('D-05', 'Kho mã & thiết bị', html, { actions: `<button class="btn btn-secondary" onclick="Admin.importModal()">${UI.icon('upload', 16)} Nhập file</button><button class="btn btn-primary" onclick="Admin.generateModal()">${UI.icon('plus', 16)} Sinh hàng loạt</button>` });
  },
  filteredCodes: function() { const f = this.st.codes; const q = f.q.toLowerCase(); return Store.codes().filter(c => (!f.status || c.status === f.status) && (!q || c.code.toLowerCase().includes(q) || (c.deviceSerial || '').toLowerCase().includes(q) || (c.orderId || '').toLowerCase().includes(q) || c.batch.toLowerCase().includes(q))).sort((a, b) => (a.stockedAt || '') < (b.stockedAt || '') ? 1 : -1); },
  renderCodes: function() { const el = document.getElementById('k-table'); if (!el) return; const list = this.filteredCodes(); const pg = UI.paginate(list, this.st.codes.page, 20); if (!list.length) { el.innerHTML = UI.empty('key', 'Không có mã phù hợp', 'Thử đổi bộ lọc hoặc từ khoá.'); return; } el.innerHTML = `<div class="table-wrap"><table class="table"><thead><tr><th>Mã sản phẩm</th><th>Mã kích hoạt</th><th>Đơn</th><th>Thành viên bán</th><th>Ngày nhập kho</th><th>Trạng thái</th><th></th></tr></thead><tbody>${pg.rows.map(c => { const a = c.agentId ? Store.user(c.agentId) : null; return `<tr><td><span class="cell-main mono">${UI.esc(c.deviceSku)}</span><span class="cell-sub mono">${UI.esc(c.deviceSerial || '')}</span></td><td class="mono">${UI.esc(c.code)}</td><td>${c.orderId ? (Store.order(c.orderId) ? `<button class="btn-link mono" onclick="Admin.orderDrawer('${c.orderId}')">${UI.esc(c.orderId)}</button>` : '<span class="mono">' + UI.esc(c.orderId) + '</span>') : '—'}</td><td>${a ? UI.esc(a.fullName) : '—'}</td><td>${UI.date(c.stockedAt)}<span class="cell-sub mono">${UI.esc(c.batch)}</span></td><td>${UI.badge('license', c.status)}</td><td><div class="row-actions"><button class="btn btn-secondary btn-sm" onclick="Admin.codeDrawer('${c.code}')">Chi tiết</button></div></td></tr>`; }).join('')}</tbody></table></div>${UI.pagination(pg, 'Admin.gotoCodes')}`; },
  gotoCodes: function(p) { this.st.codes.page = p; this.renderCodes(); },
  exportCodes: function() { UI.exportCsv('kho-ma.csv', ['Mã SP', 'Serial', 'Mã kích hoạt', 'Trạng thái', 'Lô', 'Đơn', 'Thành viên bán', 'Nhập kho', 'Gắn đơn', 'Kích hoạt', 'Thiết bị'], this.filteredCodes().map(c => [c.deviceSku, c.deviceSerial || '', c.code, LABELS.license[c.status].text, c.batch, c.orderId || '', c.agentId && Store.user(c.agentId) ? Store.user(c.agentId).fullName : '', UI.dt(c.stockedAt), UI.dt(c.assignedAt), UI.dt(c.activatedAt), c.device ? c.device.name : ''])); },
  codeDrawer: function(code) { const c = Store.codeInfo(code); const o = c.orderId ? Store.order(c.orderId) : null; const a = c.agentId ? Store.user(c.agentId) : null; UI.drawer({ title: `<h2 class="mono">${UI.esc(c.code)}</h2><div class="row-wrap mt-1">${UI.badge('license', c.status, true)}<span class="mono text-sm text-muted">${UI.esc(c.deviceSku)} · ${UI.esc(c.deviceSerial || '')}</span></div>`, body: `<div class="section"><div class="section-title">Vòng đời (một chiều)</div><div class="steps">${['IN_STOCK', 'ASSIGNED', 'ACTIVATED'].map((s, i) => `<div class="step ${c.status === s ? 'is-active' : ''} ${['IN_STOCK', 'ASSIGNED', 'ACTIVATED'].indexOf(c.status) > i ? 'is-done' : ''}"><span class="step-dot">${i + 1}</span><span>${LABELS.license[s].text}</span></div>${i < 2 ? '<span class="step-line"></span>' : ''}`).join('')}</div><dl class="dl mt-4"><dt>Nhập kho</dt><dd>${UI.dt(c.stockedAt)} · lô ${UI.esc(c.batch)}</dd><dt>Gắn đơn</dt><dd>${c.assignedAt ? UI.dt(c.assignedAt) + ' · <span class="mono">' + UI.esc(c.orderId) + '</span>' : '—'}</dd><dt>Thành viên bán</dt><dd>${a ? UI.esc(a.fullName) + ' · ' + UI.badge('rank', a.rank) : '—'}</dd><dt>Người mua</dt><dd>${o ? UI.esc(o.fullName) + ' · <span class="mono">' + UI.esc(o.phone) + '</span>' : '—'}</dd><dt>Kích hoạt</dt><dd>${c.activatedAt ? UI.dt(c.activatedAt) + ' · ' + UI.esc(c.device.name) + ' · <span class="mono">' + UI.esc(c.device.deviceId) + '</span>' : '—'}</dd></dl></div>`, foot: `${c.status === 'ASSIGNED' ? `<button class="btn btn-primary" onclick="Store.activateCode('${c.code}', { name: 'Samsung Galaxy A54 (mô phỏng)' }); UI.toast('Đã mô phỏng kích hoạt từ app.'); Admin.renderCodes(); Admin.codeDrawer('${c.code}')">${UI.icon('device', 16)} Mô phỏng kích hoạt từ app</button>` : ''}${o ? `<button class="btn btn-secondary" onclick="Admin.orderDrawer('${o.id}')">Xem đơn</button>` : ''}` }); },
  generateModal: function() { UI.modal({ title: 'Sinh mã hàng loạt', sticky: true, body: `${UI.field({ id: 'gen-n', label: 'Số lượng', required: true, mono: true, value: 100, attrs: 'inputmode="numeric"' })}<div class="mt-4">${UI.field({ id: 'gen-sku', label: 'Mã sản phẩm thiết bị', required: true, mono: true, value: CONFIG.stock.deviceSku })}</div><p class="text-caption mt-2">Serial sinh tự động dạng ${CONFIG.stock.deviceSku}-000001; mã kích hoạt ${CONFIG.stock.codePrefix}-XXXX-XXXX-XXXX không trùng.</p>`, foot: `<button class="btn btn-secondary" onclick="UI.closeModal()">Huỷ</button><button class="btn btn-primary" onclick="Admin.generate()">Sinh mã</button>` }); },
  generate: function() { const n = Number(UI.val('gen-n')); const sku = UI.val('gen-sku').toUpperCase(); UI.setError('gen-n', ''); if (!(n >= 1 && n <= 5000)) { UI.setError('gen-n', 'Nhập số từ 1 đến 5000.'); return; } const b = Store.generateCodes(n, sku); UI.closeModal(); UI.toast('Đã sinh ' + n + ' mã, lô ' + b + '.'); App.reload(); },
  importModal: function() { UI.modal({ title: 'Nhập mã từ file', sticky: true, body: `<div class="dropzone" onclick="document.getElementById('imp-file').click()">${UI.icon('upload', 28)}<div class="mt-2">Chọn file .csv (mỗi dòng: mã kích hoạt;serial thiết bị)</div><input type="file" id="imp-file" accept=".csv,.txt" hidden onchange="Admin.readImportFile(this)"></div><div class="mt-4">${UI.field({ id: 'imp-sku', label: 'Mã sản phẩm thiết bị', mono: true, value: CONFIG.stock.deviceSku })}</div><div class="mt-4">${UI.field({ id: 'imp-text', label: 'Hoặc dán danh sách', type: 'textarea', rows: 5, placeholder: 'HOMI-AB12-CD34-EF56;HW01-001301\nHOMI-…' })}</div>`, foot: `<button class="btn btn-secondary" onclick="UI.closeModal()">Huỷ</button><button class="btn btn-primary" onclick="Admin.importCodes()">Nhập vào kho</button>` }); },
  readImportFile: function(input) { const f = input.files[0]; if (!f) return; const r = new FileReader(); r.onload = () => { document.getElementById('imp-text').value = String(r.result); }; r.readAsText(f); },
  importCodes: function() { const rows = UI.val('imp-text').split(/\n+/).map(l => l.trim()).filter(Boolean).map(l => { const [code, serial] = l.split(/[;,\t]/).map(x => (x || '').trim().toUpperCase()); return { code, deviceSerial: serial }; }); UI.setError('imp-text', ''); const bad = rows.filter(r => !/^[A-Z0-9]{4}(-[A-Z0-9]{4}){3}$/.test(r.code)); if (!rows.length) { UI.setError('imp-text', 'Chưa có mã nào.'); return; } if (bad.length) { UI.setError('imp-text', bad.length + ' mã sai định dạng, ví dụ: ' + bad[0].code); return; } const r = Store.importCodes(rows, UI.val('imp-sku').toUpperCase()); UI.closeModal(); UI.toast(`Đã nhập ${r.added} mã (bỏ qua ${r.skipped} trùng), lô ${r.batch}.`); App.reload(); },

  // =====================================================================
  // D-06 · Hạng & quy tắc chương trình
  // =====================================================================
  D06: function() {
    const r = Store.rules(); const head = this.isHead();
    const html = `<div class="split-2 split-2-eq"><div class="stack">
        <div class="card"><div class="card-head"><h2>Bảng hạng thành viên</h2><span class="text-sm text-muted">Ngưỡng = tổng gói bán luỹ kế [cần xác nhận]</span></div><div class="card-body"><div class="table-wrap"><table class="table" style="min-width:0"><thead><tr><th>Hạng</th><th class="num">Ngưỡng luỹ kế</th><th class="num">Bước</th><th>Quyền tuyển thành viên</th></tr></thead><tbody>${CONFIG.ranks.map((k, i) => `<tr><td>${UI.badge('rank', k.id)}</td><td class="num mono">${k.threshold} gói</td><td class="num mono">${i ? '+' + (k.threshold - CONFIG.ranks[i - 1].threshold) : '—'}</td><td>${k.canRecruit ? '<span class="badge badge-success">Được tuyển</span>' : '<span class="badge badge-neutral">Chỉ bán</span>'}</td></tr>`).join('')}</tbody></table></div><p class="text-caption mt-2">Ngưỡng hạng cấu hình tại <span class="mono">CONFIG.ranks</span> (chờ khách chốt 10/18/24/28/30).</p></div></div>
        <div class="card"><div class="card-head"><h2>Quy tắc chương trình</h2></div><div class="card-body"><form novalidate onsubmit="Admin.saveRules(event)"><div class="form-grid form-grid-2">${UI.field({ id: 'rl-min', label: 'Bán tối thiểu / tháng để giữ hạng', mono: true, value: r.rankRules.minSalesPerMonth, attrs: head ? '' : 'readonly' })}${UI.field({ id: 'rl-steps', label: 'Số bậc giáng khi không đạt', mono: true, value: r.rankRules.demoteSteps, attrs: head ? '' : 'readonly' })}${UI.field({ id: 'rl-maxwd', label: 'Số lần rút tối đa / tháng', mono: true, value: r.withdraw.maxPerMonth, attrs: head ? '' : 'readonly' })}${UI.field({ id: 'rl-points', label: 'Tỷ lệ điểm (điểm / 1đ hoa hồng)', mono: true, value: CONFIG.points.perVnd, attrs: 'readonly' })}<div style="grid-column:1/-1">${UI.field({ id: 'rl-payout', label: 'Ghi chú thời điểm chi trả', value: r.withdraw.payoutNote, attrs: head ? '' : 'readonly' })}</div></div><div class="check mt-3"><input type="checkbox" id="rl-reset" ${r.rankRules.demoteResetsCumulative ? 'checked' : ''} ${head ? '' : 'disabled'}> Giáng hạng reset luỹ kế [cần xác nhận]</div>${head ? `<div class="mt-4">${UI.field({ id: 'rl-note', label: 'Ghi chú thay đổi', placeholder: 'Lý do…' })}</div><div class="actions"><button class="btn btn-primary">Lưu quy tắc</button></div>` : '<p class="text-caption mt-3">Chỉ Head Admin được sửa.</p>'}</form></div></div>
      </div><div class="stack">
        <div class="card"><div class="card-head"><h2>Điều khoản & điều kiện (T&C)</h2><span class="badge badge-navy badge-plain">v${UI.esc(r.tc.version)} · ${UI.esc(r.tc.updatedAt)}</span></div><div class="card-body"><form novalidate onsubmit="Admin.saveTc(event)">${UI.field({ id: 'tc-ver', label: 'Phiên bản mới', mono: true, value: (parseFloat(r.tc.version) + 0.1).toFixed(1), attrs: head ? '' : 'readonly' })}<div class="mt-3">${UI.field({ id: 'tc-text', label: 'Nội dung', type: 'textarea', rows: 12, value: r.tc.text, attrs: head ? '' : 'readonly' })}</div>${head ? `<div class="actions"><button class="btn btn-primary">Lưu T&C phiên bản mới</button></div>` : ''}</form><p class="text-caption mt-2">Thành viên đăng ký sau ngày hiệu lực chấp nhận phiên bản mới; phiên bản đã chấp nhận lưu trong hồ sơ.</p></div></div>
        <div class="card"><div class="card-head"><h2>Lịch sử thay đổi</h2></div><div class="card-body"><ul class="timeline">${(r.history || []).map(h => `<li><span class="timeline-time">${UI.dt(h.at)}</span><span class="timeline-text"><strong>${UI.esc(h.by)}</strong> · ${UI.esc(h.note)}</span></li>`).join('')}</ul></div></div>
      </div></div>`;
    return App.adminShell('D-06', 'Hạng & quy tắc chương trình', html);
  },
  saveRules: function(e) { e.preventDefault(); if (!this.isHead()) return; const patch = { rankRules: { minSalesPerMonth: Number(UI.val('rl-min')) || 1, demoteSteps: Number(UI.val('rl-steps')) || 1, demoteResetsCumulative: document.getElementById('rl-reset').checked }, withdraw: { maxPerMonth: Number(UI.val('rl-maxwd')) || 1, payoutNote: UI.val('rl-payout') } }; Store.saveRankRules(patch, this.me(), UI.val('rl-note') || 'Cập nhật quy tắc chương trình'); UI.toast('Đã lưu quy tắc.'); App.reload(); },
  saveTc: function(e) { e.preventDefault(); if (!this.isHead()) return; const v = UI.val('tc-ver'), t = UI.val('tc-text'); if (!v || t.length < 20) { UI.toast('Nhập phiên bản và nội dung.', 'warning'); return; } Store.saveTc(t, v, this.me()); UI.toast('Đã lưu T&C v' + v + '.'); App.reload(); },

  // =====================================================================
  // D-07 · Rút tiền (duyệt 2 lớp) & Sổ hoa hồng
  // =====================================================================
  D07: function(q) {
    if (q.get('tab')) this.st.d07.tab = q.get('tab') === 'ledger' ? 'ledger' : 'withdraw'; const s = this.st.d07;
    const html = `<div class="card"><div class="tabs" role="tablist" style="padding:0 20px"><button class="tab ${s.tab === 'withdraw' ? 'is-active' : ''}" onclick="Admin.st.d07.tab='withdraw'; App.reload()">${UI.icon('cash', 18)} Rút tiền <span class="count">${Store.withdrawals().filter(w => w.status.startsWith('PENDING')).length}</span></button><button class="tab ${s.tab === 'ledger' ? 'is-active' : ''}" onclick="Admin.st.d07.tab='ledger'; App.reload()">${UI.icon('layers', 18)} Sổ hoa hồng</button></div><div class="card-body" id="d07-body"></div></div>`;
    App.after(() => s.tab === 'withdraw' ? this.renderWithdrawTab() : this.renderLedgerTab());
    return App.adminShell('D-07', 'Rút tiền & sổ hoa hồng', html);
  },
  filteredWd: function() { const s = this.st.d07; return Store.withdrawals().filter(w => !s.wdStatus || w.status === s.wdStatus).sort((a, b) => a.createdAt < b.createdAt ? 1 : -1); },
  renderWithdrawTab: function() {
    const el = document.getElementById('d07-body'); if (!el) return; const s = this.st.d07; const list = this.filteredWd(); const pg = UI.paginate(list, s.wdPage);
    el.innerHTML = `<div class="alert alert-info mb-4">${UI.icon('info', 18)}<div class="text-sm">Duyệt <strong>2 lớp</strong>: Specialist thứ nhất → Chờ duyệt (1/2) → Specialist thứ hai (khác người) → Đã duyệt; Head Admin xác nhận 1 lần là đủ. Sau khi chuyển khoản, bấm <strong>Đánh dấu đã chi trả</strong>. Từ chối phải nêu lý do — thành viên thấy tại C-03 và số tiền hoàn về khả dụng.</div></div>
      <div class="table-toolbar"><div class="field"><label class="field-label" for="wd-status">Trạng thái</label><select class="select" id="wd-status" onchange="Admin.st.d07.wdStatus=this.value; Admin.st.d07.wdPage=1; Admin.renderWithdrawTab()"><option value="">Tất cả (5 trạng thái)</option>${Object.keys(LABELS.withdrawal).map(k => `<option value="${k}" ${s.wdStatus === k ? 'selected' : ''}>${LABELS.withdrawal[k].text}</option>`).join('')}</select></div><div class="toolbar-actions"><button class="btn btn-secondary" onclick="Admin.wdExportBank()">${UI.icon('download', 16)} File ngân hàng (đã duyệt)</button><button class="btn btn-secondary" onclick="Admin.exportWd()">${UI.icon('download', 16)} Xuất Excel</button></div></div>
      ${list.length ? `<div class="table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Thành viên</th><th class="num">Số tiền</th><th>Đối chiếu số dư</th><th>Nhận về</th><th>Tiến trình</th><th>Hành động</th></tr></thead><tbody>${pg.rows.map(w => { const u = Store.user(w.sellerId); const wal = Store.wallet(u.id); const okBal = wal.available >= 0; const cb = this.canApproveBtn(w); return `<tr><td class="mono">${UI.esc(w.id)}<span class="cell-sub">${UI.dt(w.createdAt)}</span></td><td><span class="cell-main">${UI.esc(u.fullName)}</span><span class="cell-sub">${UI.badge('rank', u.rank)} <span class="mono">${UI.esc(u.phone)}</span></span></td><td class="num mono text-strong">${UI.money(w.amount)}</td><td>${w.status.startsWith('PENDING') ? `<span class="${okBal ? 'text-success' : 'text-error'}">${UI.icon(okBal ? 'check-circle' : 'x-circle', 14)} ${okBal ? 'Đủ số dư' : 'Thiếu số dư'}</span><span class="cell-sub">ghi nhận ${UI.money(wal.recorded)} · giữ ${UI.money(wal.held)} · đã rút ${UI.money(wal.withdrawn)}</span>` : '<span class="text-muted">—</span>'}</td><td>${UI.esc(w.bank.bankName)}<span class="cell-sub mono">${UI.esc(w.bank.accountNo)} · ${UI.esc(w.bank.owner)}</span></td><td>${this.approvalCell(w)}</td><td><div class="row-actions">${w.status.startsWith('PENDING') ? `<button class="btn btn-success btn-sm" ${cb.ok && okBal ? '' : 'disabled'} title="${cb.why || (okBal ? '' : 'Thiếu số dư')}" onclick="Admin.wdApprove('${w.id}')">Xác nhận</button><button class="btn btn-danger-outline btn-sm" onclick="Admin.wdReject('${w.id}')">Từ chối</button>` : ''}${w.status === 'APPROVED' ? `<button class="btn btn-primary btn-sm" onclick="Admin.wdPaid('${w.id}')">Đánh dấu đã chi trả</button>` : ''}<button class="btn btn-secondary btn-sm" onclick="Admin.wdDrawer('${w.id}')">Chi tiết</button></div></td></tr>`; }).join('')}</tbody></table></div>${UI.pagination(pg, 'Admin.gotoWd')}` : UI.empty('cash', 'Không có yêu cầu rút tiền')}`;
  },
  gotoWd: function(p) { this.st.d07.wdPage = p; this.renderWithdrawTab(); },
  wdApprove: function(id) { const w = Store.withdrawal(id); const u = Store.user(w.sellerId); const me = this.me(); UI.confirm({ title: 'Xác nhận yêu cầu rút tiền', body: me.role === 'HEAD' ? 'Head Admin xác nhận → yêu cầu <strong>Đã duyệt</strong> ngay, chờ chi trả.' : (w.status === 'PENDING_0' ? 'Xác nhận lớp 1. Cần thêm một Specialist khác (hoặc Head Admin) xác nhận lớp 2.' : 'Xác nhận lớp 2 → yêu cầu <strong>Đã duyệt</strong>, chờ chi trả.'), summary: [['Thành viên', UI.esc(u.fullName)], ['Số tiền', '<strong>' + UI.money(w.amount) + '</strong>'], ['Nhận về', UI.esc(w.bank.bankName) + ' · <span class="mono">' + UI.esc(w.bank.accountNo) + '</span>'], ['Chủ TK', UI.esc(w.bank.owner)]], confirmText: 'Xác nhận', onConfirm: () => { const r = Store.approveWithdrawal(id, me); if (!r.ok) { UI.toast(r.message, 'error'); return; } UI.toast(r.status === 'APPROVED' ? 'Đã duyệt ' + id + ' — chờ chi trả.' : 'Đã xác nhận lớp 1 (1/2).'); this.renderWithdrawTab(); } }); },
  wdReject: function(id) { const w = Store.withdrawal(id); const u = Store.user(w.sellerId); UI.confirm({ title: 'Từ chối yêu cầu rút tiền', body: `${UI.money(w.amount)} hoàn về số dư khả dụng của <strong>${UI.esc(u.fullName)}</strong>. Thành viên thấy lý do tại màn Ví.`, reason: 'Lý do từ chối', confirmText: 'Từ chối', tone: 'danger', onConfirm: (reason) => { Store.rejectWithdrawal(id, this.me(), reason); UI.toast('Đã từ chối ' + id + '.', 'warning'); this.renderWithdrawTab(); } }); },
  wdPaid: function(id) { const w = Store.withdrawal(id); UI.confirm({ title: 'Đánh dấu đã chi trả', body: 'Xác nhận đã chuyển khoản cho thành viên. Ví và sổ hoa hồng được cập nhật, không hoàn tác.', summary: [['Yêu cầu', '<span class="mono">' + id + '</span>'], ['Số tiền', '<strong>' + UI.money(w.amount) + '</strong>']], confirmText: 'Đã chi trả', onConfirm: () => { const r = Store.markWithdrawalPaid(id, this.me()); if (!r.ok) { UI.toast(r.message, 'error'); return; } UI.toast('Đã ghi nhận chi trả ' + id + '.'); this.renderWithdrawTab(); } }); },
  wdDrawer: function(id) { const w = Store.withdrawal(id); const u = Store.user(w.sellerId); const wal = Store.wallet(u.id); UI.drawer({ title: `<h2 class="mono">${UI.esc(w.id)}</h2><div class="row-wrap mt-1">${UI.badge('withdrawal', w.status, true)}<span class="text-strong">${UI.money(w.amount)}</span></div>`, body: `<div class="section"><div class="section-title">Thành viên</div><dl class="dl"><dt>Họ tên</dt><dd>${UI.esc(u.fullName)} ${UI.badge('rank', u.rank)}</dd><dt>SĐT</dt><dd class="mono">${UI.esc(u.phone)}</dd><dt>Số dư</dt><dd>Ghi nhận ${UI.money(wal.recorded)} · giữ ${UI.money(wal.held)} · đã rút ${UI.money(wal.withdrawn)} · khả dụng ${UI.money(wal.available)}</dd></dl></div><div class="section"><div class="section-title">Tài khoản nhận</div><dl class="dl"><dt>Ngân hàng</dt><dd>${UI.esc(w.bank.bankName)}</dd><dt>Số TK</dt><dd class="mono">${UI.esc(w.bank.accountNo)}</dd><dt>Chủ TK</dt><dd>${UI.esc(w.bank.owner)}</dd></dl></div><div class="section"><div class="section-title">Tiến trình duyệt</div>${this.timeline(w, w.status === 'PAID' ? [{ at: w.paidAt, text: 'Đã chi trả bởi ' + w.paidBy }] : [])}</div><div class="section"><div class="section-title">Audit</div>${this.auditList('withdrawal', id)}</div>`, foot: `${w.status.startsWith('PENDING') ? `<button class="btn btn-danger-outline" onclick="Admin.wdReject('${id}')">Từ chối</button><button class="btn btn-success" ${this.canApproveBtn(w).ok ? '' : 'disabled'} onclick="Admin.wdApprove('${id}')">Xác nhận</button>` : ''}${w.status === 'APPROVED' ? `<button class="btn btn-primary" onclick="Admin.wdPaid('${id}')">Đánh dấu đã chi trả</button>` : ''}` }); },
  wdExportBank: function() { const list = Store.withdrawals().filter(w => w.status === 'APPROVED'); if (!list.length) { UI.toast('Không có yêu cầu nào đã duyệt chờ chi trả.', 'warning'); return; } UI.exportCsv('chi-tra-rut-tien-' + Store.nowIso().slice(0, 10) + '.csv', ['STT', 'Thành viên', 'Ngân hàng', 'Số TK', 'Chủ TK', 'Số tiền', 'Nội dung'], list.map((w, i) => [i + 1, Store.user(w.sellerId).fullName, w.bank.bankName, w.bank.accountNo, w.bank.owner, w.amount, 'HOMI365 HH ' + w.id])); },
  exportWd: function() { UI.exportCsv('rut-tien.csv', ['Mã', 'Ngày', 'Thành viên', 'SĐT', 'Số tiền', 'Ngân hàng', 'Số TK', 'Trạng thái', 'Xác nhận', 'Lý do'], this.filteredWd().map(w => [w.id, UI.dt(w.createdAt), Store.user(w.sellerId).fullName, Store.user(w.sellerId).phone, w.amount, w.bank.bankName, w.bank.accountNo, LABELS.withdrawal[w.status].text, (w.approvals || []).map(a => a.by + ':' + a.action).join(' '), (w.approvals.find(a => a.action === 'REJECT') || {}).reason || ''])); },
  renderLedgerTab: function() {
    const el = document.getElementById('d07-body'); if (!el) return; const s = this.st.d07; const q = s.cmQ.toLowerCase();
    const list = Store.commissions().filter(c => !q || c.orderId.toLowerCase().includes(q) || (c.beneficiaryId !== 'COMPANY' && Store.user(c.beneficiaryId) && Store.user(c.beneficiaryId).fullName.toLowerCase().includes(q)) || (c.beneficiaryId === 'COMPANY' && 'công ty'.includes(q))).sort((a, b) => a.createdAt < b.createdAt ? 1 : -1);
    const pg = UI.paginate(list, s.cmPage, 15); const total = list.filter(c => c.status === 'RECORDED').reduce((t, c) => t + c.amount, 0); const company = list.filter(c => c.beneficiaryId === 'COMPANY' && c.status === 'RECORDED').reduce((t, c) => t + c.amount, 0);
    el.innerHTML = `<div class="alert alert-neutral mb-4">${UI.icon('info', 18)}<div class="text-sm">Sổ hoa hồng <strong>chỉ đọc</strong>: mỗi khoản ghi nhận ngay khi đơn thanh toán theo bảng hoa hồng hiệu lực; không có bước duyệt hoa hồng. Kiểm tra Σ theo đơn tại chi tiết đơn (D-03).</div></div>
      <div class="table-toolbar"><div class="field field-search"><label class="field-label" for="cm-q">Tìm theo thành viên / đơn</label><input class="input" id="cm-q" value="${UI.esc(s.cmQ)}" oninput="Admin.st.d07.cmQ=this.value; Admin.st.d07.cmPage=1; Admin.renderLedgerTab()"></div><div class="toolbar-actions"><span class="text-sm text-muted">Tổng ghi nhận ${UI.money(total)} · về công ty ${UI.money(company)}</span><button class="btn btn-secondary" onclick="Admin.exportCm()">${UI.icon('download', 16)} Xuất Excel</button></div></div>
      ${list.length ? `<div class="table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Ngày</th><th>Đơn</th><th>Người thụ hưởng</th><th>Cấp</th><th>Hạng lúc tính</th><th class="num">Số tiền</th><th>TT</th></tr></thead><tbody>${pg.rows.map(c => `<tr><td class="mono">${UI.esc(c.id)}</td><td>${UI.date(c.createdAt)}</td><td><button class="btn-link mono" onclick="Admin.orderDrawer('${c.orderId}')">${UI.esc(c.orderId)}</button></td><td>${c.beneficiaryId === 'COMPANY' ? '<strong>HOMI365</strong>' : UI.esc(Store.user(c.beneficiaryId).fullName)}</td><td>${UI.badge('commissionKind', c.kind)}${c.kind === 'DIFF' ? ' <span class="text-sm text-muted">F' + c.depth + '</span>' : ''}</td><td>${UI.badge('rank', c.rankAtCalc)}</td><td class="num mono text-strong">${UI.money(c.amount)}</td><td>${UI.badge('commission', c.status)}</td></tr>`).join('')}</tbody></table></div>${UI.pagination(pg, 'Admin.gotoCm')}` : UI.empty('layers', 'Không có khoản hoa hồng')}`;
  },
  gotoCm: function(p) { this.st.d07.cmPage = p; this.renderLedgerTab(); },
  exportCm: function() { UI.exportCsv('so-hoa-hong.csv', ['Mã', 'Ngày', 'Đơn', 'Người thụ hưởng', 'Cấp', 'Depth', 'Hạng lúc tính', 'Số tiền', 'Trạng thái'], Store.commissions().map(c => [c.id, UI.dt(c.createdAt), c.orderId, c.beneficiaryId === 'COMPANY' ? 'HOMI365' : Store.user(c.beneficiaryId).fullName, LABELS.commissionKind[c.kind].text, c.depth, RULES.rank(c.rankAtCalc).label, c.amount, LABELS.commission[c.status].text])); },

  // =====================================================================
  // D-08 · Cấp phát ngoại lệ (ẩn khi rules.onePackagePerPhone=false)
  // =====================================================================
  D08: function() { return App.adminShell('D-08', 'Cấp phát ngoại lệ', `<div class="card"><div class="card-body">${UI.empty('gift', 'Quy tắc 1 gói / 1 SĐT đang tắt', 'Bật CONFIG.rules.onePackagePerPhone để dùng màn này.')}</div></div>`); },

  // =====================================================================
  // D-09 · Duyệt đăng ký thành viên (7.9.2)
  // =====================================================================
  D09: function() {
    const f = this.st.regs;
    const html = `<div class="card"><div class="card-body"><div class="alert alert-info mb-4">${UI.icon('info', 18)}<div class="text-sm">Duyệt <strong>2 lớp</strong> (người thứ 2 phải khác người thứ 1; Head Admin tự chốt). Khi <strong>Đã duyệt</strong>: tạo tài khoản thành viên hạng Copper, sinh ref_code + link cá nhân, gửi email kích hoạt. Duyệt không ảnh hưởng đơn, tuyến và hoa hồng đã ghi.</div></div>
      <div class="table-toolbar"><div class="field field-search"><label class="field-label" for="rg-q">Tìm kiếm</label><input class="input" id="rg-q" placeholder="Họ tên, SĐT, email" value="${UI.esc(f.q)}" oninput="Admin.st.regs.q=this.value; Admin.st.regs.page=1; Admin.renderRegs()"></div><div class="field"><label class="field-label" for="rg-status">Trạng thái</label><select class="select" id="rg-status" onchange="Admin.st.regs.status=this.value; Admin.st.regs.page=1; Admin.renderRegs()"><option value="">Tất cả</option>${Object.keys(LABELS.approval).map(k => `<option value="${k}" ${f.status === k ? 'selected' : ''}>${LABELS.approval[k].text}</option>`).join('')}</select></div></div>
      <div id="rg-table">${UI.skeletonTable(7, 5)}</div></div></div>`;
    App.after(() => UI.withLoading('rg-table', UI.skeletonTable(7, 5), () => this.renderRegs()));
    return App.adminShell('D-09', 'Duyệt đăng ký thành viên', html);
  },
  filteredRegs: function() { const f = this.st.regs; const q = f.q.toLowerCase(); return Store.registrations().filter(r => (!f.status || r.status === f.status) && (!q || r.fullName.toLowerCase().includes(q) || r.phone.includes(q) || r.email.toLowerCase().includes(q))).sort((a, b) => a.createdAt < b.createdAt ? 1 : -1); },
  renderRegs: function() {
    const el = document.getElementById('rg-table'); if (!el) return; const list = this.filteredRegs(); const pg = UI.paginate(list, this.st.regs.page);
    if (!list.length) { el.innerHTML = UI.empty('user', 'Không có hồ sơ', 'Chưa có đăng ký nào ở trạng thái này.'); return; }
    el.innerHTML = `<div class="table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Người đăng ký</th><th>Người giới thiệu</th><th>Đơn gốc</th><th>Ngày nộp</th><th>Tiến trình</th><th>Hành động</th></tr></thead><tbody>${pg.rows.map(r => { const ref = r.referrerId ? Store.user(r.referrerId) : null; const cb = this.canApproveBtn(r); return `<tr><td class="mono">${UI.esc(r.id)}</td><td><span class="cell-main">${UI.esc(r.fullName)}</span><span class="cell-sub mono">${UI.esc(r.phone)}</span><span class="cell-sub">${UI.esc(r.email)}</span></td><td>${ref ? UI.esc(ref.fullName) + '<span class="cell-sub"><span class="mono">' + UI.esc(ref.refCode) + '</span> · ' + RULES.rank(r.referrerRankAtSubmit || ref.rank).label + ' lúc nộp</span>' : '—'}</td><td><button class="btn-link mono" onclick="Admin.orderDrawer('${r.orderId}')">${UI.esc(r.orderId)}</button></td><td>${UI.dt(r.createdAt)}</td><td>${this.approvalCell(r)}</td><td><div class="row-actions">${r.status.startsWith('PENDING') ? `<button class="btn btn-success btn-sm" ${cb.ok ? '' : 'disabled'} title="${cb.why || ''}" onclick="Admin.regApprove('${r.id}')">Xác nhận</button><button class="btn btn-danger-outline btn-sm" onclick="Admin.regReject('${r.id}')">Từ chối</button>` : ''}<button class="btn btn-secondary btn-sm" onclick="Admin.regDrawer('${r.id}')">Chi tiết</button></div></td></tr>`; }).join('')}</tbody></table></div>${UI.pagination(pg, 'Admin.gotoRegs')}`;
  },
  gotoRegs: function(p) { this.st.regs.page = p; this.renderRegs(); },
  regApprove: function(id) { const r = Store.registration(id); const me = this.me(); UI.confirm({ title: 'Xác nhận hồ sơ đăng ký', body: me.role === 'HEAD' ? 'Head Admin xác nhận → <strong>Đã duyệt</strong>: kích hoạt thành viên ngay.' : (r.status === 'PENDING_0' ? 'Xác nhận lớp 1. Cần một admin khác xác nhận lớp 2 để kích hoạt.' : 'Xác nhận lớp 2 → <strong>Đã duyệt</strong>: kích hoạt thành viên ngay.'), summary: [['Họ tên', UI.esc(r.fullName)], ['SĐT', '<span class="mono">' + UI.esc(r.phone) + '</span>'], ['Email', UI.esc(r.email)], ['Người giới thiệu', r.referrerId ? UI.esc(Store.user(r.referrerId).fullName) : '—']], confirmText: 'Xác nhận', onConfirm: () => { const res = Store.approveRegistration(id, me); if (!res.ok) { UI.toast(res.message, 'error'); return; } if (res.status === 'APPROVED') { UI.toast('Đã duyệt — kích hoạt thành viên ' + res.agent.fullName + '.'); this.renderRegs(); this.regDrawer(id); } else { UI.toast('Đã xác nhận lớp 1 (1/2).'); this.renderRegs(); } } }); },
  regReject: function(id) { const r = Store.registration(id); UI.confirm({ title: 'Từ chối hồ sơ', body: `Hồ sơ của <strong>${UI.esc(r.fullName)}</strong> chuyển sang Từ chối. Người đăng ký thấy lý do khi đăng nhập và ${CONFIG.rules.rejectedCanResubmit ? 'có thể nộp lại' : 'không thể nộp lại'}.`, reason: 'Lý do từ chối', confirmText: 'Từ chối', tone: 'danger', onConfirm: (reason) => { Store.rejectRegistration(id, this.me(), reason); UI.toast('Đã từ chối ' + id + '.', 'warning'); this.renderRegs(); } }); },
  regDrawer: function(id) { const r = Store.registration(id); const ref = r.referrerId ? Store.user(r.referrerId) : null; const o = Store.order(r.orderId); const agent = r.agentId ? Store.user(r.agentId) : null; const mail = agent ? Store.emails().find(e => e.to === agent.email) : null; UI.drawer({ title: `<h2>${UI.esc(r.fullName)}</h2><div class="row-wrap mt-1">${UI.badge('approval', r.status, true)}<span class="mono text-sm text-muted">${UI.esc(r.id)}</span></div>`, body: `<div class="section"><div class="section-title">Hồ sơ đã nộp</div><dl class="dl"><dt>SĐT</dt><dd class="mono">${UI.esc(r.phone)}</dd><dt>Email</dt><dd>${UI.esc(r.email)}</dd><dt>Ngân hàng</dt><dd>${UI.esc(r.bank.bankName)} · <span class="mono">${UI.esc(r.bank.accountNo)}</span> · ${UI.esc(r.bank.owner)}</dd><dt>T&C</dt><dd>v${UI.esc(r.tcVersion)} · ${UI.dt(r.tcAt)}</dd><dt>Nộp lúc</dt><dd>${UI.dt(r.createdAt)}</dd></dl></div><div class="section"><div class="section-title">Người giới thiệu & đơn gốc</div><dl class="dl"><dt>Người giới thiệu</dt><dd>${ref ? UI.esc(ref.fullName) + ' · <span class="mono">' + UI.esc(ref.refCode) + '</span> · ' + UI.badge('rank', ref.rank) + ' (lúc nộp: ' + RULES.rank(r.referrerRankAtSubmit || ref.rank).label + ')' : '—'}</dd><dt>Đơn</dt><dd>${o ? '<span class="mono">' + UI.esc(o.id) + '</span> · ' + UI.money(o.price) + ' · ' + UI.date(o.paidAt) : '—'}</dd></dl></div><div class="section"><div class="section-title">Tiến trình</div>${this.timeline(r)}</div>${agent ? `<div class="section"><div class="section-title">Đã kích hoạt</div><dl class="dl"><dt>ref_code</dt><dd class="mono">${UI.esc(agent.refCode)}</dd><dt>Link cá nhân</dt><dd class="mono">${UI.esc(RULES.publicPurchaseUrl(agent.purchaseAlias))}</dd><dt>Hạng</dt><dd>${UI.badge('rank', agent.rank)}</dd></dl>${mail ? `<div class="alert alert-success mt-3">${UI.icon('sms', 18)}<div class="text-sm"><span class="alert-title">Email kích hoạt (mock) → ${UI.esc(mail.to)}</span><pre style="white-space:pre-wrap;font-family:inherit;margin-top:6px">${UI.esc(mail.body)}</pre></div></div>` : ''}</div>` : ''}<div class="section"><div class="section-title">Audit</div>${this.auditList('registration', id)}</div>`, foot: `${r.status.startsWith('PENDING') ? `<button class="btn btn-danger-outline" onclick="Admin.regReject('${id}')">Từ chối</button><button class="btn btn-success" ${this.canApproveBtn(r).ok ? '' : 'disabled'} onclick="Admin.regApprove('${id}')">Xác nhận</button>` : ''}${agent ? `<button class="btn btn-secondary" onclick="Admin.userDrawer('${agent.id}')">Xem thành viên</button>` : ''}` }); },

  // =====================================================================
  // D-10 · Tài khoản admin (Head Admin)
  // =====================================================================
  D10: function() {
    const me = this.me(); const list = Store.adminUsers();
    const html = `<div class="card"><div class="card-body"><div class="table-wrap"><table class="table"><thead><tr><th>Tên đăng nhập</th><th>Họ tên</th><th>Vai trò</th><th>Trạng thái</th><th>Tạo bởi</th><th></th></tr></thead><tbody>${list.map(a => `<tr><td class="mono text-strong">${UI.esc(a.username)}${a.username === me.username ? ' <span class="badge badge-navy badge-plain">bạn</span>' : ''}</td><td>${UI.esc(a.fullName)}</td><td>${UI.badge('role', a.role)}</td><td>${UI.badge('adminStatus', a.status)}</td><td>${UI.esc(a.createdBy)}<span class="cell-sub">${UI.date(a.createdAt)}</span></td><td><div class="row-actions"><button class="btn btn-secondary btn-sm" onclick="Admin.adminForm('${a.username}')">${UI.icon('edit', 14)} Sửa</button>${a.username !== me.username ? (a.status === 'active' ? `<button class="btn btn-danger-outline btn-sm" onclick="Admin.setAdminStatus('${a.username}', 'disabled')">Vô hiệu</button>` : `<button class="btn btn-success btn-sm" onclick="Admin.setAdminStatus('${a.username}', 'active')">Kích hoạt</button>`) : ''}</div></td></tr>`).join('')}</tbody></table></div><p class="text-caption mt-3">Head Admin không thể tự hạ vai trò hoặc vô hiệu chính mình. Specialist truy cập màn này bị từ chối (403).</p></div></div>`;
    return App.adminShell('D-10', 'Tài khoản admin', html, { actions: `<button class="btn btn-primary" onclick="Admin.adminForm()">${UI.icon('plus', 16)} Thêm tài khoản</button>` });
  },
  adminForm: function(username) { const a = username ? Store.adminUsers().find(x => x.username === username) : null; const me = this.me(); UI.modal({ title: a ? 'Sửa tài khoản ' + a.username : 'Thêm tài khoản admin', sticky: true, body: `${UI.field({ id: 'am-user', label: 'Tên đăng nhập', required: true, mono: true, value: a ? a.username : '', attrs: a ? 'readonly' : '' })}<div class="mt-4">${UI.field({ id: 'am-name', label: 'Họ tên', required: true, value: a ? a.fullName : '' })}</div><div class="mt-4">${UI.field({ id: 'am-role', label: 'Vai trò', type: 'select', value: a ? a.role : 'SPECIALIST', options: [{ value: 'SPECIALIST', label: LABELS.role.SPECIALIST.text }, { value: 'HEAD', label: LABELS.role.HEAD.text }], attrs: a && a.username === me.username ? 'disabled' : '' })}</div><div class="mt-4">${UI.field({ id: 'am-pw', label: a ? 'Đặt lại mật khẩu (để trống nếu giữ)' : 'Mật khẩu', required: !a, type: 'password' })}</div>`, foot: `<button class="btn btn-secondary" onclick="UI.closeModal()">Huỷ</button><button class="btn btn-primary" onclick="Admin.saveAdmin(${a ? 'true' : 'false'})">Lưu</button>` }); },
  saveAdmin: function(editing) { const username = UI.val('am-user'), fullName = UI.val('am-name'), role = document.getElementById('am-role').value, pw = UI.val('am-pw'); ['am-user', 'am-name', 'am-pw'].forEach(x => UI.setError(x, '')); let ok = true; if (!/^[a-z0-9_.]{3,20}$/.test(username)) { UI.setError('am-user', '3–20 ký tự thường/số.'); ok = false; } if (!editing && Store.adminUsers().some(a => a.username === username)) { UI.setError('am-user', 'Đã tồn tại.'); ok = false; } if (!fullName) { UI.setError('am-name', 'Nhập họ tên.'); ok = false; } if ((!editing || pw) && RULES.validatePassword(pw)) { UI.setError('am-pw', RULES.validatePassword(pw)); ok = false; } if (!ok) return; Store.saveAdminUser({ username, fullName, role, password: pw }, this.me()); UI.closeModal(); UI.toast('Đã lưu tài khoản ' + username + '.'); App.reload(); },
  setAdminStatus: function(username, status) { UI.confirm({ title: status === 'disabled' ? 'Vô hiệu tài khoản?' : 'Kích hoạt lại?', body: `Tài khoản <span class="mono">${UI.esc(username)}</span> ${status === 'disabled' ? 'sẽ không đăng nhập được.' : 'đăng nhập trở lại.'}`, confirmText: status === 'disabled' ? 'Vô hiệu' : 'Kích hoạt', tone: status === 'disabled' ? 'danger' : '', onConfirm: () => { Store.setAdminStatus(username, status, this.me()); UI.toast('Đã cập nhật.'); App.reload(); } }); }
};
